struct Instance1 {
  status2: Unit;
  info3: Double;
  min4: Unit;
  result5: Array[Double];
  y6: Array[Unit];
}

struct Queue7 {
  bottom8: Double;
  a9: Array[Unit];
  z10: Unit;
  x11: Array[Bool];
  value12: Double;
}

struct Result13 {
  k14: Array[Bool];
  a15: (Int, Int);
  i16: Int;
  left17: (Double, Unit);
}

enum Instance18 {
  Queue19(Array[Unit]);
  Buffer20;
}

enum Structure21 {
  Matrix22(Double);
  Wrapper23(Unit, Bool, Array[Int]);
  Context24;
}

let item25: Array[Array[Unit]] = [[(), (), (), (), (), (), (), (), ()], [(), (), (), (), (), (), (), (), (), ()], [(), (), (), (), (), (), (), ()], Array::make(6, ()), Array::make(10, ()), [(), (), (), (), (), (), ()], Array::make(8, ())];

let top26: Bool = if true {
    true
  } else {
    false
  };

fn head27(z28: Int, index29: Int) -> Int {
  let _ = {
    let mut flag30: Int = 0;
    while flag30 < 4 {
    if false {
    ()
  } else {
    ()
  };
    let data31 = Array::make(10, true);
    flag30 = flag30 + 1;
  }
  };
  let mut status32: Int = z28;
  status32 = 412;
  status32 = 7;
  let bottom33: Array[Bool] = Array::make(8, top26);
  status32 = 60592;
  let mut max34: (Bool, Double) = (true, 36.60294189095148);
  max34 = max34;
  let mut head35 = 965.7803842174882;
  head35 = 290.78306458079174;
  let (c36, temp37, _): (Bool, Int, Int) = (top26, 2, 910);
  let c38: Bool = true;
  let b39: Unit = ();
  let _ = {
    let mut x40: Int = 0;
    while x40 < 4 {
    let z41: Int = 1 / temp37;
    match (80213, top26) {
    (2, _) => b39;
    _ => b39;
  };
    let temp42 = 5;
    x40 = x40 + 1;
  }
  };
  max34 = (false, head35);
  max34 = (true, 332.4890279020929);
  let (_, status43, index44) = (846.0211460236342, (), 396.1530710981684);
  let info45: Int = 910;
  let (value46, _): (Int, Unit) = (543, b39);
  let i47: Bool = 8 <= 293;
  max34 = (false, index44);
  let _ = {
    let mut node48: Int = 0;
    while node48 < 5 {
    let a49: Int = -1;
    node48 = node48 + 1;
  }
  };
  let mut elem50 = 392;
  elem50 = z28;
  head35 = head35;
  let next51 = Array::make(7, 10088);
  max34 = max34;
  max34 = max34;
  let _ = {
    let mut data52: Int = 0;
    while data52 < 1 {
    if false {
    ()
  } else {
    ()
  };
    data52 = data52 + 1;
  }
  };
  elem50 = index29;
  elem50 = temp37;
  let mut temp53 = head35 % 591.3114462379426;
  temp53 = 270.5503266593195;
  let _ = {
    let mut index54: Int = 0;
    while index54 < 1 {
    let _ = ();
    let head55: Unit = ();
    index54 = index54 + 1;
  }
  };
  let status56 = ();
  let mut k57: Int = 3;
  k57 = index29;
  let flag58: Instance1 = Instance1::{status2: (), info3: 622.4329629567064, min4: (), result5: Array::make(7, 527.122657788708), y6: [(), (), (), (), (), (), (), (), (), ()]};
  let _ = flag58.status2;
  let _ = flag58.info3;
  let _ = flag58.min4;
  let _ = flag58.result5;
  let _ = flag58.y6;
  let _ = flag58;
  let tail59: Queue7 = Queue7::{bottom8: 292.7409004666263, a9: [(), (), (), (), (), (), ()], z10: (), x11: [true, false, true, true, false, false, true], value12: 67.42101918226618};
  let _ = tail59.bottom8;
  let _ = tail59.a9;
  let _ = tail59.z10;
  let _ = tail59.x11;
  let _ = tail59.value12;
  let _ = tail59;
  let index60: Result13 = Result13::{k14: [true, false, top26, true, false, top26, false], a15: (index29, -1), i16: 982, left17: (214.69873993486988, ())};
  let _ = index60.k14;
  let _ = index60.a15;
  let _ = print_int(index60.i16);
  let _ = index60.left17;
  let _ = index60;
  let b61: Instance18 = Instance18::Queue19(Array::make(8, ()));
  match b61 {
    Instance18::Queue19(_) => ();
    Instance18::Buffer20 => ();
  };
  let _ = b61;
  let temp62: Structure21 = Structure21::Wrapper23((), false, [129, 3, 5, 0, -1, 6, index29, index29]);
  match temp62 {
    Structure21::Matrix22(_) => ();
    Structure21::Wrapper23(_, _, _) => ();
    Structure21::Context24 => ();
  };
  let _ = temp62;
  let _ = print_int(z28);
  let _ = print_int(index29);
  -1
}

let info63: Int = -1;

struct Matrix64 {
  last65: Bool;
  index66: Double;
  next67: Double;
  last68: Double;
  a69: Int;
}

struct Queue70 {
  tail71: Unit;
  min72: Double;
}

let info73: Int = 9;

enum Data74 {
  Entity75(Int, Double, Int);
  Config76(Unit, Int, Bool);
  Tree77;
  Queue78(Int, Unit);
}

enum Matrix79 {
  Result80;
  Record81(Array[Double]);
}

struct State82 {
  max83: Double;
  min84: Array[Double];
  bottom85: Unit;
  last86: Unit;
  sum87: Unit;
}

let value88: Int = info73;

enum Vector89 {
  Instance90(Bool, Double);
  Complex91;
  Container92(Int, Unit, Bool);
}

enum List93 {
  Queue94(Bool, Int);
  Structure95(Bool, Bool, Array[Unit]);
  Value96(Bool);
}

fn status97(result98: Unit) -> Double {
  let mut target99: Bool = true;
  target99 = true;
  let min100: Bool = false;
  target99 = false;
  target99 = false;
  target99 = true;
  let next101: Bool = true;
  target99 = min100;
  let c102: Bool = top26 || top26;
  match false {
    true => ();
    false => ();
  };
  let left103: Int = 1;
  let (first104, _, y105): (Bool, Bool, Bool) = (true, target99, next101);
  let mut x106 = 338.25889845811486 + 832.2234371399866;
  x106 = x106;
  target99 = false;
  x106 = 635.8702936771003;
  let mut index107: Array[Double] = Array::make(7, x106);
  index107 = index107;
  let mut status108: Int = info73;
  status108 = status108;
  let max109: Int = head27(-1, 83374);
  x106 = x106;
  let mut j110 = [756, 5, 2, max109, 21623, 849, value88, status108, 9, 4];
  j110 = [-1, 5, 7, -1, 3, value88, 8, status108, 42282];
  index107 = Array::make(7, 231.41166254501545);
  index107 = index107;
  j110 = j110;
  let sum111: Unit = ();
  let status112: Double = 14.97857657681001;
  let max113 = status112;
  match next101 {
    true => ();
    false => ();
  };
  let target114: Instance1 = Instance1::{status2: (), info3: 313.08247753619787, min4: (), result5: [144.7106711719468, 855.1412888183556, 206.47297875704496, 227.59892070437238, 998.0193385794246, 584.2833657421565, 40.61845984199108, 390.14445912827057], y6: Array::make(8, ())};
  let _ = target114.status2;
  let _ = target114.info3;
  let _ = target114.min4;
  let _ = target114.result5;
  let _ = target114.y6;
  let _ = target114;
  let elem115: Queue7 = Queue7::{bottom8: 115.70823810298714, a9: Array::make(7, ()), z10: (), x11: [true, top26, true, true, top26, false], value12: 8.170853986583682};
  let _ = elem115.bottom8;
  let _ = elem115.a9;
  let _ = elem115.z10;
  let _ = elem115.x11;
  let _ = elem115.value12;
  let _ = elem115;
  let z116: Result13 = Result13::{k14: [true, top26, true, true, true, top26], a15: (-1, 73473), i16: 8, left17: (184.71699798364583, result98)};
  let _ = z116.k14;
  let _ = z116.a15;
  let _ = print_int(z116.i16);
  let _ = z116.left17;
  let _ = z116;
  let data117: Matrix64 = Matrix64::{last65: top26, index66: 236.49926252044295, next67: 804.0424972098634, last68: 443.4410921850724, a69: info73};
  let _ = data117.last65;
  let _ = data117.index66;
  let _ = data117.next67;
  let _ = data117.last68;
  let _ = print_int(data117.a69);
  let _ = data117;
  let item118: Queue70 = Queue70::{tail71: (), min72: 82.50374761980983};
  let _ = item118.tail71;
  let _ = item118.min72;
  let _ = item118;
  let j119: State82 = State82::{max83: 720.7487191726545, min84: [479.3526475883022, 498.9478250678371, 324.8594538042879, 540.6405788131293, 938.2802955149632, 237.70345475776955, 940.0762055385687, 150.7646972687623], bottom85: result98, last86: (), sum87: ()};
  let _ = j119.max83;
  let _ = j119.min84;
  let _ = j119.bottom85;
  let _ = j119.last86;
  let _ = j119.sum87;
  let _ = j119;
  let index120: Instance18 = Instance18::Buffer20;
  match index120 {
    Instance18::Queue19(_) => ();
    Instance18::Buffer20 => ();
  };
  let _ = index120;
  let status121: Structure21 = Structure21::Wrapper23(result98, false, Array::make(6, info63));
  match status121 {
    Structure21::Matrix22(_) => ();
    Structure21::Wrapper23(_, _, _) => ();
    Structure21::Context24 => ();
  };
  let _ = status121;
  let info122: Data74 = Data74::Entity75(info73, 787.2866279968418, value88);
  match info122 {
    Data74::Entity75(_, _, _) => ();
    Data74::Config76(_, _, _) => ();
    Data74::Tree77 => ();
    Data74::Queue78(_, _) => ();
  };
  let _ = info122;
  let sum123: Matrix79 = Matrix79::Result80;
  match sum123 {
    Matrix79::Result80 => ();
    Matrix79::Record81(_) => ();
  };
  let _ = sum123;
  let right124: Vector89 = Vector89::Container92(7, (), top26);
  match right124 {
    Vector89::Instance90(_, _) => ();
    Vector89::Complex91 => ();
    Vector89::Container92(_, _, _) => ();
  };
  let _ = right124;
  let next125: List93 = List93::Queue94(top26, value88);
  match next125 {
    List93::Queue94(_, _) => ();
    List93::Structure95(_, _, _) => ();
    List93::Value96(_) => ();
  };
  let _ = next125;
  let result126: Int = head27(9, value88);
  let _ = print_int(result126);
  let _ = result98;
  334.6054681858164
}

let j127: Int = value88 % info63;

fn value128(top129: Unit, last130: Bool) -> Bool {
  let data131: Int = 5;
  let top132: Int = 923 % 9;
  let temp133: Double = 935.0470585649203;
  let prev134: Bool = true;
  let first135: Double = temp133;
  let flag136: Bool = false;
  let head137: Unit = ();
  let i138 = j127;
  let node139: Unit = ();
  let _ = {
    let mut count140: Int = 0;
    while count140 < 1 {
    let sum141: Array[Unit] = Array::make(10, ());
    let info142: Double = 200.49139851409925;
    count140 = count140 + 1;
  }
  };
  let sum143: Bool = false;
  let (_, _, prev144) = (node139, true, 697.6662026621931);
  let temp145 = sum143;
  let _ = ();
  let mut a146: Unit = ();
  a146 = a146;
  let mut left147: Bool = false;
  left147 = last130;
  let result148 = ();
  let mut sum149: Array[Double] = Array::make(7, 470.8151952885955);
  sum149 = Array::make(10, prev144);
  let mut i150 = true;
  i150 = false;
  let k151 = (result148);
  let item152: Bool = true;
  let x153: Unit = ();
  let flag154 = value88;
  let first155: Instance1 = Instance1::{status2: top129, info3: 33.26868887061618, min4: (), result5: [154.60173232402718, 498.32411574920275, 78.38146854575324, 784.0137921621094, 9.658493809150293, 689.7014988324329, 898.8792365280284, 893.3354103389344], y6: Array::make(8, ())};
  let _ = first155.status2;
  let _ = first155.info3;
  let _ = first155.min4;
  let _ = first155.result5;
  let _ = first155.y6;
  let _ = first155;
  let prev156: Queue7 = Queue7::{bottom8: 795.6629989563105, a9: Array::make(7, ()), z10: (), x11: [top26, true, true, true, true, top26], value12: 380.51043636305906};
  let _ = prev156.bottom8;
  let _ = prev156.a9;
  let _ = prev156.z10;
  let _ = prev156.x11;
  let _ = prev156.value12;
  let _ = prev156;
  let top157: Result13 = Result13::{k14: [false, true, top26, last130, true, true, false, true], a15: (12889, 387), i16: value88, left17: (675.5750644197334, ())};
  let _ = top157.k14;
  let _ = top157.a15;
  let _ = print_int(top157.i16);
  let _ = top157.left17;
  let _ = top157;
  let prev158: Matrix64 = Matrix64::{last65: top26, index66: 124.61297696943197, next67: 669.6327488444377, last68: 973.8081469079882, a69: info63};
  let _ = prev158.last65;
  let _ = prev158.index66;
  let _ = prev158.next67;
  let _ = prev158.last68;
  let _ = print_int(prev158.a69);
  let _ = prev158;
  let count159: Queue70 = Queue70::{tail71: (), min72: 216.2837350271668};
  let _ = count159.tail71;
  let _ = count159.min72;
  let _ = count159;
  let j160: State82 = State82::{max83: 704.1937932877363, min84: Array::make(10, 341.3451044700407), bottom85: (), last86: top129, sum87: ()};
  let _ = j160.max83;
  let _ = j160.min84;
  let _ = j160.bottom85;
  let _ = j160.last86;
  let _ = j160.sum87;
  let _ = j160;
  let j161: Instance18 = Instance18::Buffer20;
  match j161 {
    Instance18::Queue19(_) => ();
    Instance18::Buffer20 => ();
  };
  let _ = j161;
  let target162: Structure21 = Structure21::Context24;
  match target162 {
    Structure21::Matrix22(_) => ();
    Structure21::Wrapper23(_, _, _) => ();
    Structure21::Context24 => ();
  };
  let _ = target162;
  let a163: Data74 = Data74::Entity75(30884, 493.83300043007904, j127);
  match a163 {
    Data74::Entity75(_, _, _) => ();
    Data74::Config76(_, _, _) => ();
    Data74::Tree77 => ();
    Data74::Queue78(_, _) => ();
  };
  let _ = a163;
  let c164: Matrix79 = Matrix79::Record81(Array::make(7, 578.926895741242));
  match c164 {
    Matrix79::Result80 => ();
    Matrix79::Record81(_) => ();
  };
  let _ = c164;
  let left165: Vector89 = Vector89::Instance90(true, 627.2993040821871);
  match left165 {
    Vector89::Instance90(_, _) => ();
    Vector89::Complex91 => ();
    Vector89::Container92(_, _, _) => ();
  };
  let _ = left165;
  let tail166: List93 = List93::Queue94(false, value88);
  match tail166 {
    List93::Queue94(_, _) => ();
    List93::Structure95(_, _, _) => ();
    List93::Value96(_) => ();
  };
  let _ = tail166;
  let sum167: Int = head27(499, info63);
  let _ = print_int(sum167);
  let head168: Double = status97(());
  let _ = head168;
  let _ = top129;
  let _ = last130;
  false
}

fn info169(flag170: Int, left171: Unit) -> Double {
  let mut b172 = ();
  b172 = ();
  let mut b173 = top26;
  b173 = false;
  let current174 = 272.7789868671785 / 640.6554368872341;
  let value175: Double = status97(());
  b172 = left171;
  return 918.3830927069342;
  b172 = ();
  let status176: Instance1 = Instance1::{status2: (), info3: 861.5232127966348, min4: left171, result5: [441.8813128451203, 227.73494400574046, 117.12437085713357, 710.0148191070701, 257.95265189739735, 475.7447899482996, 52.49821827490542, 458.2407400224534, 695.6329462143591], y6: Array::make(7, ())};
  let _ = status176.status2;
  let _ = status176.info3;
  let _ = status176.min4;
  let _ = status176.result5;
  let _ = status176.y6;
  let _ = status176;
  let max177: Queue7 = Queue7::{bottom8: 960.5673148842659, a9: Array::make(7, ()), z10: (), x11: [top26, true, top26, true, false, false, true, top26], value12: 362.48937136109004};
  let _ = max177.bottom8;
  let _ = max177.a9;
  let _ = max177.z10;
  let _ = max177.x11;
  let _ = max177.value12;
  let _ = max177;
  let bottom178: Result13 = Result13::{k14: [top26, top26, true, true, false, top26, false, top26, true, false], a15: (flag170, 5), i16: -1, left17: (843.9963844425738, left171)};
  let _ = bottom178.k14;
  let _ = bottom178.a15;
  let _ = print_int(bottom178.i16);
  let _ = bottom178.left17;
  let _ = bottom178;
  let left179: Matrix64 = Matrix64::{last65: top26, index66: 286.8952784731985, next67: 278.44304893041385, last68: 405.4611505291172, a69: 2};
  let _ = left179.last65;
  let _ = left179.index66;
  let _ = left179.next67;
  let _ = left179.last68;
  let _ = print_int(left179.a69);
  let _ = left179;
  let count180: Queue70 = Queue70::{tail71: (), min72: 316.7640206647635};
  let _ = count180.tail71;
  let _ = count180.min72;
  let _ = count180;
  let sum181: State82 = State82::{max83: 51.13747149324554, min84: Array::make(6, 413.0380746460275), bottom85: (), last86: (), sum87: ()};
  let _ = sum181.max83;
  let _ = sum181.min84;
  let _ = sum181.bottom85;
  let _ = sum181.last86;
  let _ = sum181.sum87;
  let _ = sum181;
  let count182: Instance18 = Instance18::Queue19(Array::make(8, ()));
  match count182 {
    Instance18::Queue19(_) => ();
    Instance18::Buffer20 => ();
  };
  let _ = count182;
  let z183: Structure21 = Structure21::Context24;
  match z183 {
    Structure21::Matrix22(_) => ();
    Structure21::Wrapper23(_, _, _) => ();
    Structure21::Context24 => ();
  };
  let _ = z183;
  let y184: Data74 = Data74::Config76(left171, 959, true);
  match y184 {
    Data74::Entity75(_, _, _) => ();
    Data74::Config76(_, _, _) => ();
    Data74::Tree77 => ();
    Data74::Queue78(_, _) => ();
  };
  let _ = y184;
  let k185: Matrix79 = Matrix79::Record81([398.2279248049203, 981.4587170365718, 595.5037935355442, 9.874336375486292, 212.2382388850488, 730.454175985975]);
  match k185 {
    Matrix79::Result80 => ();
    Matrix79::Record81(_) => ();
  };
  let _ = k185;
  let min186: Vector89 = Vector89::Container92(27049, left171, true);
  match min186 {
    Vector89::Instance90(_, _) => ();
    Vector89::Complex91 => ();
    Vector89::Container92(_, _, _) => ();
  };
  let _ = min186;
  let x187: List93 = List93::Value96(false);
  match x187 {
    List93::Queue94(_, _) => ();
    List93::Structure95(_, _, _) => ();
    List93::Value96(_) => ();
  };
  let _ = x187;
  let right188: Int = head27(j127, 18109);
  let _ = print_int(right188);
  let left189: Double = status97(left171);
  let _ = left189;
  let tail190: Bool = value128((), true);
  let _ = tail190;
  let _ = print_int(flag170);
  let _ = left171;
  908.6291006982681
}

struct Result191 {
  sum192: Int;
  info193: (Bool, Int, Int);
  bottom194: Double;
  target195: Bool;
  y196: Double;
}

fn data197() -> Double {
  let next198: Bool = top26;
  let count199: Instance1 = Instance1::{status2: (), info3: 707.9462275862286, min4: (), result5: Array::make(7, 843.3962465502343), y6: Array::make(8, ())};
  let _ = count199.status2;
  let _ = count199.info3;
  let _ = count199.min4;
  let _ = count199.result5;
  let _ = count199.y6;
  let _ = count199;
  let j200: Queue7 = Queue7::{bottom8: 764.2167573607386, a9: [(), (), (), (), (), (), ()], z10: (), x11: Array::make(10, false), value12: 996.3105159852827};
  let _ = j200.bottom8;
  let _ = j200.a9;
  let _ = j200.z10;
  let _ = j200.x11;
  let _ = j200.value12;
  let _ = j200;
  let prev201: Result13 = Result13::{k14: [true, true, top26, top26, true, true], a15: (info73, 1), i16: 5, left17: (843.7305168564119, ())};
  let _ = prev201.k14;
  let _ = prev201.a15;
  let _ = print_int(prev201.i16);
  let _ = prev201.left17;
  let _ = prev201;
  let value202: Matrix64 = Matrix64::{last65: false, index66: 644.0459137528438, next67: 750.2187733378273, last68: 92.08348561754698, a69: j127};
  let _ = value202.last65;
  let _ = value202.index66;
  let _ = value202.next67;
  let _ = value202.last68;
  let _ = print_int(value202.a69);
  let _ = value202;
  let b203: Queue70 = Queue70::{tail71: (), min72: 920.9442470678462};
  let _ = b203.tail71;
  let _ = b203.min72;
  let _ = b203;
  let index204: State82 = State82::{max83: 39.20567082620108, min84: Array::make(6, 397.12145932188434), bottom85: (), last86: (), sum87: ()};
  let _ = index204.max83;
  let _ = index204.min84;
  let _ = index204.bottom85;
  let _ = index204.last86;
  let _ = index204.sum87;
  let _ = index204;
  let index205: Result191 = Result191::{sum192: 743, info193: (top26, 5, -1), bottom194: 515.9711816882705, target195: true, y196: 796.1177756554376};
  let _ = print_int(index205.sum192);
  let _ = index205.info193;
  let _ = index205.bottom194;
  let _ = index205.target195;
  let _ = index205.y196;
  let _ = index205;
  let head206: Instance18 = Instance18::Buffer20;
  match head206 {
    Instance18::Queue19(_) => ();
    Instance18::Buffer20 => ();
  };
  let _ = head206;
  let elem207: Structure21 = Structure21::Matrix22(311.07544972686816);
  match elem207 {
    Structure21::Matrix22(_) => ();
    Structure21::Wrapper23(_, _, _) => ();
    Structure21::Context24 => ();
  };
  let _ = elem207;
  let right208: Data74 = Data74::Tree77;
  match right208 {
    Data74::Entity75(_, _, _) => ();
    Data74::Config76(_, _, _) => ();
    Data74::Tree77 => ();
    Data74::Queue78(_, _) => ();
  };
  let _ = right208;
  let b209: Matrix79 = Matrix79::Result80;
  match b209 {
    Matrix79::Result80 => ();
    Matrix79::Record81(_) => ();
  };
  let _ = b209;
  let sum210: Vector89 = Vector89::Complex91;
  match sum210 {
    Vector89::Instance90(_, _) => ();
    Vector89::Complex91 => ();
    Vector89::Container92(_, _, _) => ();
  };
  let _ = sum210;
  let i211: List93 = List93::Queue94(true, -1);
  match i211 {
    List93::Queue94(_, _) => ();
    List93::Structure95(_, _, _) => ();
    List93::Value96(_) => ();
  };
  let _ = i211;
  let value212: Int = head27(29, 6355);
  let _ = print_int(value212);
  let bottom213: Double = status97(());
  let _ = bottom213;
  let tail214: Bool = value128((), true);
  let _ = tail214;
  let elem215: Double = info169(1, ());
  let _ = elem215;
  740.6701945420689
}

fn result216() -> Unit {
  let status217: Unit = ();
  let data218: Instance1 = Instance1::{status2: (), info3: 40.73231518893494, min4: (), result5: Array::make(9, 689.776173608508), y6: Array::make(7, ())};
  let _ = data218.status2;
  let _ = data218.info3;
  let _ = data218.min4;
  let _ = data218.result5;
  let _ = data218.y6;
  let _ = data218;
  let index219: Queue7 = Queue7::{bottom8: 444.2753549584029, a9: [(), (), (), (), (), (), (), (), (), ()], z10: (), x11: [false, top26, top26, true, true, true, true, false, true, top26], value12: 900.1659366112503};
  let _ = index219.bottom8;
  let _ = index219.a9;
  let _ = index219.z10;
  let _ = index219.x11;
  let _ = index219.value12;
  let _ = index219;
  let target220: Result13 = Result13::{k14: Array::make(7, top26), a15: (3, info63), i16: 66263, left17: (323.6356614261607, ())};
  let _ = target220.k14;
  let _ = target220.a15;
  let _ = print_int(target220.i16);
  let _ = target220.left17;
  let _ = target220;
  let tail221: Matrix64 = Matrix64::{last65: top26, index66: 862.3975546157866, next67: status97(()), last68: 27.87683187373069, a69: -1};
  let _ = tail221.last65;
  let _ = tail221.index66;
  let _ = tail221.next67;
  let _ = tail221.last68;
  let _ = print_int(tail221.a69);
  let _ = tail221;
  let min222: Queue70 = Queue70::{tail71: (), min72: 714.8528802798787};
  let _ = min222.tail71;
  let _ = min222.min72;
  let _ = min222;
  let left223: State82 = State82::{max83: 924.7104904492503, min84: [768.9782511236555, 610.6340087074967, 923.3441371060525, status97(()), 50.54295511638407, 554.4926994205551, 467.14752222743715, 984.4524366473711, 173.50529149105688, 650.5932238416177], bottom85: (), last86: (), sum87: ()};
  let _ = left223.max83;
  let _ = left223.min84;
  let _ = left223.bottom85;
  let _ = left223.last86;
  let _ = left223.sum87;
  let _ = left223;
  let prev224: Result191 = Result191::{sum192: 53143, info193: (true, value88, 492), bottom194: 224.48735157135613, target195: true, y196: 109.62864733822886};
  let _ = print_int(prev224.sum192);
  let _ = prev224.info193;
  let _ = prev224.bottom194;
  let _ = prev224.target195;
  let _ = prev224.y196;
  let _ = prev224;
  let x225: Instance18 = Instance18::Buffer20;
  match x225 {
    Instance18::Queue19(_) => ();
    Instance18::Buffer20 => ();
  };
  let _ = x225;
  let last226: Structure21 = Structure21::Wrapper23((), false, Array::make(6, j127));
  match last226 {
    Structure21::Matrix22(_) => ();
    Structure21::Wrapper23(_, _, _) => ();
    Structure21::Context24 => ();
  };
  let _ = last226;
  let status227: Data74 = Data74::Queue78(269, ());
  match status227 {
    Data74::Entity75(_, _, _) => ();
    Data74::Config76(_, _, _) => ();
    Data74::Tree77 => ();
    Data74::Queue78(_, _) => ();
  };
  let _ = status227;
  let temp228: Matrix79 = Matrix79::Record81(Array::make(6, 392.748050346275));
  match temp228 {
    Matrix79::Result80 => ();
    Matrix79::Record81(_) => ();
  };
  let _ = temp228;
  let a229: Vector89 = Vector89::Container92(info73, (), false);
  match a229 {
    Vector89::Instance90(_, _) => ();
    Vector89::Complex91 => ();
    Vector89::Container92(_, _, _) => ();
  };
  let _ = a229;
  let max230: List93 = List93::Queue94(false, 1);
  match max230 {
    List93::Queue94(_, _) => ();
    List93::Structure95(_, _, _) => ();
    List93::Value96(_) => ();
  };
  let _ = max230;
  let data231: Int = head27(1, 3);
  let _ = print_int(data231);
  let last232: Double = status97(());
  let _ = last232;
  let top233: Bool = value128((), true);
  let _ = top233;
  let z234: Double = info169(66399, ());
  let _ = z234;
  let index235: Double = data197();
  let _ = index235;
}

struct Vector236 {
  top237: Unit;
  x238: Bool;
  bottom239: Double;
}

let head240: Int = 6646;

struct Stack241 {
  top242: (Double, Double, Unit);
  a243: Double;
}

fn value244(tail245: Bool) -> Bool {
  let (y246, _, status247): (Bool, Unit, Double) = (false, (), 614.9277628802853);
  let c248: Instance1 = Instance1::{status2: (), info3: 811.2868402887183, min4: (), result5: Array::make(10, 346.05006262210634), y6: Array::make(8, ())};
  let _ = c248.status2;
  let _ = c248.info3;
  let _ = c248.min4;
  let _ = c248.result5;
  let _ = c248.y6;
  let _ = c248;
  let node249: Queue7 = Queue7::{bottom8: 935.0602467377179, a9: Array::make(9, ()), z10: (), x11: [tail245, false, true, true, false, top26], value12: 692.3405508266071};
  let _ = node249.bottom8;
  let _ = node249.a9;
  let _ = node249.z10;
  let _ = node249.x11;
  let _ = node249.value12;
  let _ = node249;
  let last250: Result13 = Result13::{k14: [true, false, true, false, false, false, false, true], a15: (1, info63), i16: head240, left17: (389.7649353903776, ())};
  let _ = last250.k14;
  let _ = last250.a15;
  let _ = print_int(last250.i16);
  let _ = last250.left17;
  let _ = last250;
  let elem251: Matrix64 = Matrix64::{last65: false, index66: 253.92007002550065, next67: 101.9904755915505, last68: 289.0184743031774, a69: -1};
  let _ = elem251.last65;
  let _ = elem251.index66;
  let _ = elem251.next67;
  let _ = elem251.last68;
  let _ = print_int(elem251.a69);
  let _ = elem251;
  let first252: Queue70 = Queue70::{tail71: (), min72: 447.4529009764461};
  let _ = first252.tail71;
  let _ = first252.min72;
  let _ = first252;
  let left253: State82 = State82::{max83: 354.9306073122481, min84: Array::make(8, 838.603711768657), bottom85: (), last86: (), sum87: ()};
  let _ = left253.max83;
  let _ = left253.min84;
  let _ = left253.bottom85;
  let _ = left253.last86;
  let _ = left253.sum87;
  let _ = left253;
  let j254: Result191 = Result191::{sum192: 7, info193: (true, head240, 5), bottom194: 295.7976293634059, target195: false, y196: 878.7213271210939};
  let _ = print_int(j254.sum192);
  let _ = j254.info193;
  let _ = j254.bottom194;
  let _ = j254.target195;
  let _ = j254.y196;
  let _ = j254;
  let bottom255: Vector236 = Vector236::{top237: (), x238: false, bottom239: 121.27506045885895};
  let _ = bottom255.top237;
  let _ = bottom255.x238;
  let _ = bottom255.bottom239;
  let _ = bottom255;
  let i256: Stack241 = Stack241::{top242: (111.60115740340338, 253.2498990108405, ()), a243: 720.4835646679887};
  let _ = i256.top242;
  let _ = i256.a243;
  let _ = i256;
  let sum257: Instance18 = Instance18::Buffer20;
  match sum257 {
    Instance18::Queue19(_) => ();
    Instance18::Buffer20 => ();
  };
  let _ = sum257;
  let value258: Structure21 = Structure21::Context24;
  match value258 {
    Structure21::Matrix22(_) => ();
    Structure21::Wrapper23(_, _, _) => ();
    Structure21::Context24 => ();
  };
  let _ = value258;
  let current259: Data74 = Data74::Queue78(98867, ());
  match current259 {
    Data74::Entity75(_, _, _) => ();
    Data74::Config76(_, _, _) => ();
    Data74::Tree77 => ();
    Data74::Queue78(_, _) => ();
  };
  let _ = current259;
  let y260: Matrix79 = Matrix79::Result80;
  match y260 {
    Matrix79::Result80 => ();
    Matrix79::Record81(_) => ();
  };
  let _ = y260;
  let sum261: Vector89 = Vector89::Instance90(false, 10.495950384578956);
  match sum261 {
    Vector89::Instance90(_, _) => ();
    Vector89::Complex91 => ();
    Vector89::Container92(_, _, _) => ();
  };
  let _ = sum261;
  let top262: List93 = List93::Structure95(true, false, Array::make(9, ()));
  match top262 {
    List93::Queue94(_, _) => ();
    List93::Structure95(_, _, _) => ();
    List93::Value96(_) => ();
  };
  let _ = top262;
  let flag263: Int = head27(138, info73);
  let _ = print_int(flag263);
  let node264: Double = status97(());
  let _ = node264;
  let count265: Bool = value128(result216(), false);
  let _ = count265;
  let last266: Double = info169(4, result216());
  let _ = last266;
  let sum267: Double = data197();
  let _ = sum267;
  let _ = result216();
  let _ = tail245;
  value128((), top26)
}

struct Entry268 {
  bottom269: Array[Int];
  k270: Bool;
  left271: Array[Unit];
}

struct Container272 {
  left273: Array[Unit];
  info274: Double;
}

struct Instance275 {
  data276: Int;
  prev277: Unit;
}

let last278: Array[Bool] = Array::make(8, top26);

let current279: Array[Double] = [145.20206155299954, 574.9574943425057, 176.2455553036536, 447.484363534561, 285.39140140944164, 656.3340811132622];

struct Stack280 {
  info281: Int;
}

struct Wrapper282 {
  bottom283: Bool;
  first284: Double;
}

let next285: Bool = !top26;

enum Data286 {
  Element287;
  Stack288(Array[Unit], Unit);
}

enum Vector289 {
  Buffer290;
}

fn count291() -> Bool {
  let b292: Array[Unit] = Array::make(6, result216());
  let i293: Instance1 = Instance1::{status2: (), info3: 332.46097570132196, min4: (), result5: Array::make(9, 527.5919098285284), y6: [(), (), (), (), (), (), (), ()]};
  let _ = i293.status2;
  let _ = i293.info3;
  let _ = i293.min4;
  let _ = i293.result5;
  let _ = i293.y6;
  let _ = i293;
  let j294: Queue7 = Queue7::{bottom8: 912.9664705855162, a9: [(), (), (), (), (), (), ()], z10: (), x11: Array::make(7, true), value12: 251.98958598571542};
  let _ = j294.bottom8;
  let _ = j294.a9;
  let _ = j294.z10;
  let _ = j294.x11;
  let _ = j294.value12;
  let _ = j294;
  let c295: Result13 = Result13::{k14: last278, a15: (18271, 176), i16: head27(info73, 3), left17: (738.5702098463576, ())};
  let _ = c295.k14;
  let _ = c295.a15;
  let _ = print_int(c295.i16);
  let _ = c295.left17;
  let _ = c295;
  let z296: Matrix64 = Matrix64::{last65: true, index66: 102.03697013068324, next67: 990.9907528665776, last68: 381.5341559074472, a69: value88};
  let _ = z296.last65;
  let _ = z296.index66;
  let _ = z296.next67;
  let _ = z296.last68;
  let _ = print_int(z296.a69);
  let _ = z296;
  let prev297: Queue70 = Queue70::{tail71: (), min72: 62.014235641242976};
  let _ = prev297.tail71;
  let _ = prev297.min72;
  let _ = prev297;
  let top298: State82 = State82::{max83: 486.8594904985041, min84: current279, bottom85: (), last86: (), sum87: ()};
  let _ = top298.max83;
  let _ = top298.min84;
  let _ = top298.bottom85;
  let _ = top298.last86;
  let _ = top298.sum87;
  let _ = top298;
  let result299: Result191 = Result191::{sum192: head27(629, j127), info193: (value128((), false), 562, info63), bottom194: 115.36609188951985, target195: true, y196: 925.2354963093834};
  let _ = print_int(result299.sum192);
  let _ = result299.info193;
  let _ = result299.bottom194;
  let _ = result299.target195;
  let _ = result299.y196;
  let _ = result299;
  let prev300: Vector236 = Vector236::{top237: (), x238: false, bottom239: 276.4218337924682};
  let _ = prev300.top237;
  let _ = prev300.x238;
  let _ = prev300.bottom239;
  let _ = prev300;
  let item301: Stack241 = Stack241::{top242: (438.13884902973297, data197(), ()), a243: 60.14802393869234};
  let _ = item301.top242;
  let _ = item301.a243;
  let _ = item301;
  let status302: Entry268 = Entry268::{bottom269: [126, 1, 148, value88, value88, 41662], k270: true, left271: [(), (), (), (), (), (), (), ()]};
  let _ = status302.bottom269;
  let _ = status302.k270;
  let _ = status302.left271;
  let _ = status302;
  let i303: Container272 = Container272::{left273: [(), (), (), (), (), (), (), (), ()], info274: 532.2705563336084};
  let _ = i303.left273;
  let _ = i303.info274;
  let _ = i303;
  let c304: Instance275 = Instance275::{data276: head240, prev277: ()};
  let _ = print_int(c304.data276);
  let _ = c304.prev277;
  let _ = c304;
  let elem305: Stack280 = Stack280::{info281: 34934};
  let _ = print_int(elem305.info281);
  let _ = elem305;
  let first306: Wrapper282 = Wrapper282::{bottom283: top26, first284: 849.4399032107212};
  let _ = first306.bottom283;
  let _ = first306.first284;
  let _ = first306;
  let i307: Instance18 = Instance18::Queue19([result216(), (), (), (), (), ()]);
  match i307 {
    Instance18::Queue19(_) => ();
    Instance18::Buffer20 => ();
  };
  let _ = i307;
  let value308: Structure21 = Structure21::Wrapper23((), true, Array::make(6, 75228));
  match value308 {
    Structure21::Matrix22(_) => ();
    Structure21::Wrapper23(_, _, _) => ();
    Structure21::Context24 => ();
  };
  let _ = value308;
  let index309: Data74 = Data74::Tree77;
  match index309 {
    Data74::Entity75(_, _, _) => ();
    Data74::Config76(_, _, _) => ();
    Data74::Tree77 => ();
    Data74::Queue78(_, _) => ();
  };
  let _ = index309;
  let a310: Matrix79 = Matrix79::Record81([533.8344461058734, 558.6959073682708, 683.9868005739999, 287.41616878185795, 369.86069165455126, 476.6368046480561, 177.54412100257534, 569.4687352168125]);
  match a310 {
    Matrix79::Result80 => ();
    Matrix79::Record81(_) => ();
  };
  let _ = a310;
  let index311: Vector89 = Vector89::Instance90(false, 134.80827169478027);
  match index311 {
    Vector89::Instance90(_, _) => ();
    Vector89::Complex91 => ();
    Vector89::Container92(_, _, _) => ();
  };
  let _ = index311;
  let max312: List93 = List93::Queue94(true, 52980);
  match max312 {
    List93::Queue94(_, _) => ();
    List93::Structure95(_, _, _) => ();
    List93::Value96(_) => ();
  };
  let _ = max312;
  let result313: Data286 = Data286::Element287;
  match result313 {
    Data286::Element287 => ();
    Data286::Stack288(_, _) => ();
  };
  let _ = result313;
  let flag314: Vector289 = Vector289::Buffer290;
  match flag314 {
    Vector289::Buffer290 => ();
  };
  let _ = flag314;
  let flag315: Int = head27(info63, head27(1, 883));
  let _ = print_int(flag315);
  let tail316: Double = status97(());
  let _ = tail316;
  let index317: Bool = value128((), false);
  let _ = index317;
  let elem318: Double = info169(j127, ());
  let _ = elem318;
  let bottom319: Double = data197();
  let _ = bottom319;
  let _ = result216();
  let j320: Bool = value244(value244(top26));
  let _ = j320;
  false
}

struct Item321 {
  count322: Unit;
  result323: Double;
  left324: Double;
  flag325: Bool;
}

let i326: Int = head27(-1, 9);

let target327: Int = match Vector289::Buffer290 {
    Vector289::Buffer290 => 415;
  };

let sum328: Int = j127 + 1;

let prev329: Bool = count291();

enum State330 {
  Point331(Bool, Bool, Int);
  Option332(Double, Int, Double);
  Point333;
  Data334;
}

let head335: Double = current279[3];

struct Container336 {
  result337: Int;
  data338: Bool;
  count339: Bool;
}

struct Value340 {
  j341: Bool;
  target342: (Double, Unit);
  next343: Unit;
  j344: Int;
}

struct Cache345 {
  index346: Array[Unit];
  result347: (Bool, Double, Double, Bool);
  status348: Unit;
  count349: Bool;
  first350: Bool;
}

fn head351(first352: Unit, count353: Bool) -> Double {
  let mut top354: Bool = next285;
  top354 = true;
  let current355: Instance1 = Instance1::{status2: result216(), info3: head335, min4: (), result5: [692.768433152041, 461.61352044443737, 913.9725000345497, head335, data197(), head335, 253.24748520049644, 410.29677435851363, head335], y6: Array::make(10, ())};
  let _ = current355.status2;
  let _ = current355.info3;
  let _ = current355.min4;
  let _ = current355.result5;
  let _ = current355.y6;
  let _ = current355;
  let left356: Queue7 = Queue7::{bottom8: head335, a9: [(), (), first352, (), (), (), (), (), (), first352], z10: first352, x11: Array::make(6, prev329), value12: head335};
  let _ = left356.bottom8;
  let _ = left356.a9;
  let _ = left356.z10;
  let _ = left356.x11;
  let _ = left356.value12;
  let _ = left356;
  let max357: Result13 = Result13::{k14: last278, a15: (682, 3), i16: sum328, left17: (head335, first352)};
  let _ = max357.k14;
  let _ = max357.a15;
  let _ = print_int(max357.i16);
  let _ = max357.left17;
  let _ = max357;
  let elem358: Matrix64 = Matrix64::{last65: prev329, index66: 18.902981200034752, next67: data197(), last68: 499.46150393952803, a69: 302};
  let _ = elem358.last65;
  let _ = elem358.index66;
  let _ = elem358.next67;
  let _ = elem358.last68;
  let _ = print_int(elem358.a69);
  let _ = elem358;
  let current359: Queue70 = Queue70::{tail71: (), min72: head335};
  let _ = current359.tail71;
  let _ = current359.min72;
  let _ = current359;
  let min360: State82 = State82::{max83: 822.8407770646686, min84: Array::make(8, 299.92690904366236), bottom85: (), last86: (), sum87: first352};
  let _ = min360.max83;
  let _ = min360.min84;
  let _ = min360.bottom85;
  let _ = min360.last86;
  let _ = min360.sum87;
  let _ = min360;
  let b361: Result191 = Result191::{sum192: info73, info193: (false, -1, 22445), bottom194: head335, target195: count291(), y196: 736.9500128346593};
  let _ = print_int(b361.sum192);
  let _ = b361.info193;
  let _ = b361.bottom194;
  let _ = b361.target195;
  let _ = b361.y196;
  let _ = b361;
  let z362: Vector236 = Vector236::{top237: first352, x238: true, bottom239: 440.88584400849317};
  let _ = z362.top237;
  let _ = z362.x238;
  let _ = z362.bottom239;
  let _ = z362;
  let last363: Stack241 = Stack241::{top242: (542.7629954949387, 12.584341981285885, first352), a243: 438.13890522535957};
  let _ = last363.top242;
  let _ = last363.a243;
  let _ = last363;
  let index364: Entry268 = Entry268::{bottom269: Array::make(7, 7), k270: false, left271: Array::make(10, ())};
  let _ = index364.bottom269;
  let _ = index364.k270;
  let _ = index364.left271;
  let _ = index364;
  let temp365: Container272 = Container272::{left273: [first352, (), result216(), (), first352, first352, first352], info274: head335};
  let _ = temp365.left273;
  let _ = temp365.info274;
  let _ = temp365;
  let current366: Instance275 = Instance275::{data276: target327, prev277: ()};
  let _ = print_int(current366.data276);
  let _ = current366.prev277;
  let _ = current366;
  let sum367: Stack280 = Stack280::{info281: 37233};
  let _ = print_int(sum367.info281);
  let _ = sum367;
  let a368: Wrapper282 = Wrapper282::{bottom283: count353, first284: 938.9641878171335};
  let _ = a368.bottom283;
  let _ = a368.first284;
  let _ = a368;
  let last369: Item321 = Item321::{count322: (), result323: 354.7269165706042, left324: 483.71723055823304, flag325: true};
  let _ = last369.count322;
  let _ = last369.result323;
  let _ = last369.left324;
  let _ = last369.flag325;
  let _ = last369;
  let count370: Container336 = Container336::{result337: 185, data338: true, count339: count353};
  let _ = print_int(count370.result337);
  let _ = count370.data338;
  let _ = count370.count339;
  let _ = count370;
  let c371: Value340 = Value340::{j341: top26, target342: (85.51848404945095, first352), next343: (), j344: i326};
  let _ = c371.j341;
  let _ = c371.target342;
  let _ = c371.next343;
  let _ = print_int(c371.j344);
  let _ = c371;
  let max372: Cache345 = Cache345::{index346: Array::make(9, ()), result347: (prev329, 379.23031413445375, head335, false), status348: first352, count349: false, first350: true};
  let _ = max372.index346;
  let _ = max372.result347;
  let _ = max372.status348;
  let _ = max372.count349;
  let _ = max372.first350;
  let _ = max372;
  let b373: Instance18 = Instance18::Queue19([(), (), (), first352, (), first352, (), (), (), ()]);
  match b373 {
    Instance18::Queue19(_) => ();
    Instance18::Buffer20 => ();
  };
  let _ = b373;
  let data374: Structure21 = Structure21::Wrapper23((), next285, [3, info73, 1, value88, 1, 495]);
  match data374 {
    Structure21::Matrix22(_) => ();
    Structure21::Wrapper23(_, _, _) => ();
    Structure21::Context24 => ();
  };
  let _ = data374;
  let j375: Data74 = Data74::Config76((), head240, true);
  match j375 {
    Data74::Entity75(_, _, _) => ();
    Data74::Config76(_, _, _) => ();
    Data74::Tree77 => ();
    Data74::Queue78(_, _) => ();
  };
  let _ = j375;
  let max376: Matrix79 = Matrix79::Result80;
  match max376 {
    Matrix79::Result80 => ();
    Matrix79::Record81(_) => ();
  };
  let _ = max376;
  let sum377: Vector89 = Vector89::Container92(value88, first352, true);
  match sum377 {
    Vector89::Instance90(_, _) => ();
    Vector89::Complex91 => ();
    Vector89::Container92(_, _, _) => ();
  };
  let _ = sum377;
  let item378: List93 = List93::Value96(top26);
  match item378 {
    List93::Queue94(_, _) => ();
    List93::Structure95(_, _, _) => ();
    List93::Value96(_) => ();
  };
  let _ = item378;
  let first379: Data286 = Data286::Element287;
  match first379 {
    Data286::Element287 => ();
    Data286::Stack288(_, _) => ();
  };
  let _ = first379;
  let prev380: Vector289 = Vector289::Buffer290;
  match prev380 {
    Vector289::Buffer290 => ();
  };
  let _ = prev380;
  let bottom381: State330 = State330::Point333;
  match bottom381 {
    State330::Point331(_, _, _) => ();
    State330::Option332(_, _, _) => ();
    State330::Point333 => ();
    State330::Data334 => ();
  };
  let _ = bottom381;
  let tail382: Int = head27(769, 5);
  let _ = print_int(tail382);
  let sum383: Double = status97(first352);
  let _ = sum383;
  let left384: Bool = value128((), next285);
  let _ = left384;
  let value385: Double = info169(39103, ());
  let _ = value385;
  let item386: Double = data197();
  let _ = item386;
  let _ = result216();
  let z387: Bool = value244(true);
  let _ = z387;
  let k388: Bool = count291();
  let _ = k388;
  let _ = first352;
  let _ = count353;
  data197()
}

struct Item389 {
  next390: Double;
}

fn main {
  let bottom391 = !top26;
  let max392: Instance1 = Instance1::{status2: (), info3: 743.0469064201736, min4: (), result5: Array::make(7, head335), y6: Array::make(8, ())};
  let _ = max392.status2;
  let _ = max392.info3;
  let _ = max392.min4;
  let _ = max392.result5;
  let _ = max392.y6;
  let _ = max392;
  let tail393: Queue7 = Queue7::{bottom8: 139.66750584262365, a9: [(), (), (), (), (), (), (), ()], z10: (), x11: [top26, top26, false, true, true, false, false, false, false], value12: head335};
  let _ = tail393.bottom8;
  let _ = tail393.a9;
  let _ = tail393.z10;
  let _ = tail393.x11;
  let _ = tail393.value12;
  let _ = tail393;
  let x394: Result13 = Result13::{k14: last278, a15: (-1, 1), i16: info73, left17: (head335, ())};
  let _ = x394.k14;
  let _ = x394.a15;
  let _ = print_int(x394.i16);
  let _ = x394.left17;
  let _ = x394;
  let value395: Matrix64 = Matrix64::{last65: false, index66: 513.1397441312275, next67: 110.89208238671333, last68: data197(), a69: 5};
  let _ = value395.last65;
  let _ = value395.index66;
  let _ = value395.next67;
  let _ = value395.last68;
  let _ = print_int(value395.a69);
  let _ = value395;
  let j396: Queue70 = Queue70::{tail71: (), min72: 684.3184744818143};
  let _ = j396.tail71;
  let _ = j396.min72;
  let _ = j396;
  let node397: State82 = State82::{max83: 307.6642359019458, min84: current279, bottom85: (), last86: (), sum87: ()};
  let _ = node397.max83;
  let _ = node397.min84;
  let _ = node397.bottom85;
  let _ = node397.last86;
  let _ = node397.sum87;
  let _ = node397;
  let count398: Result191 = Result191::{sum192: 40655, info193: (prev329, head27(74952, 96408), info73), bottom194: head335, target195: true, y196: 80.71363164933432};
  let _ = print_int(count398.sum192);
  let _ = count398.info193;
  let _ = count398.bottom194;
  let _ = count398.target195;
  let _ = count398.y196;
  let _ = count398;
  let bottom399: Vector236 = Vector236::{top237: (), x238: false, bottom239: 384.28708786098554};
  let _ = bottom399.top237;
  let _ = bottom399.x238;
  let _ = bottom399.bottom239;
  let _ = bottom399;
  let bottom400: Stack241 = Stack241::{top242: (68.37668423512466, 880.1504966102015, ()), a243: 135.59089235459166};
  let _ = bottom400.top242;
  let _ = bottom400.a243;
  let _ = bottom400;
  let count401: Entry268 = Entry268::{bottom269: Array::make(10, 6), k270: prev329, left271: Array::make(8, ())};
  let _ = count401.bottom269;
  let _ = count401.k270;
  let _ = count401.left271;
  let _ = count401;
  let right402: Container272 = Container272::{left273: Array::make(10, ()), info274: head335};
  let _ = right402.left273;
  let _ = right402.info274;
  let _ = right402;
  let j403: Instance275 = Instance275::{data276: 701, prev277: ()};
  let _ = print_int(j403.data276);
  let _ = j403.prev277;
  let _ = j403;
  let elem404: Stack280 = Stack280::{info281: 7};
  let _ = print_int(elem404.info281);
  let _ = elem404;
  let flag405: Wrapper282 = Wrapper282::{bottom283: false, first284: status97(())};
  let _ = flag405.bottom283;
  let _ = flag405.first284;
  let _ = flag405;
  let c406: Item321 = Item321::{count322: (), result323: 129.20150809606434, left324: 166.40735587121137, flag325: true};
  let _ = c406.count322;
  let _ = c406.result323;
  let _ = c406.left324;
  let _ = c406.flag325;
  let _ = c406;
  let flag407: Container336 = Container336::{result337: value88, data338: prev329, count339: true};
  let _ = print_int(flag407.result337);
  let _ = flag407.data338;
  let _ = flag407.count339;
  let _ = flag407;
  let y408: Value340 = Value340::{j341: value128((), true), target342: (200.92069449661577, ()), next343: (), j344: info73};
  let _ = y408.j341;
  let _ = y408.target342;
  let _ = y408.next343;
  let _ = print_int(y408.j344);
  let _ = y408;
  let i409: Cache345 = Cache345::{index346: [(), (), (), (), (), ()], result347: (false, head335, 843.4101248496979, false), status348: (), count349: true, first350: false};
  let _ = i409.index346;
  let _ = i409.result347;
  let _ = i409.status348;
  let _ = i409.count349;
  let _ = i409.first350;
  let _ = i409;
  let x410: Item389 = Item389::{next390: head335};
  let _ = x410.next390;
  let _ = x410;
  let elem411: Instance18 = Instance18::Queue19([(), (), (), (), (), result216(), (), (), result216(), ()]);
  match elem411 {
    Instance18::Queue19(_) => ();
    Instance18::Buffer20 => ();
  };
  let _ = elem411;
  let tail412: Structure21 = Structure21::Matrix22(784.0453715698691);
  match tail412 {
    Structure21::Matrix22(_) => ();
    Structure21::Wrapper23(_, _, _) => ();
    Structure21::Context24 => ();
  };
  let _ = tail412;
  let prev413: Data74 = Data74::Entity75(17522, 148.93804747918858, -1);
  match prev413 {
    Data74::Entity75(_, _, _) => ();
    Data74::Config76(_, _, _) => ();
    Data74::Tree77 => ();
    Data74::Queue78(_, _) => ();
  };
  let _ = prev413;
  let last414: Matrix79 = Matrix79::Result80;
  match last414 {
    Matrix79::Result80 => ();
    Matrix79::Record81(_) => ();
  };
  let _ = last414;
  let target415: Vector89 = Vector89::Complex91;
  match target415 {
    Vector89::Instance90(_, _) => ();
    Vector89::Complex91 => ();
    Vector89::Container92(_, _, _) => ();
  };
  let _ = target415;
  let index416: List93 = List93::Structure95(false, false, Array::make(10, ()));
  match index416 {
    List93::Queue94(_, _) => ();
    List93::Structure95(_, _, _) => ();
    List93::Value96(_) => ();
  };
  let _ = index416;
  let elem417: Data286 = Data286::Stack288(Array::make(6, ()), ());
  match elem417 {
    Data286::Element287 => ();
    Data286::Stack288(_, _) => ();
  };
  let _ = elem417;
  let flag418: Vector289 = Vector289::Buffer290;
  match flag418 {
    Vector289::Buffer290 => ();
  };
  let _ = flag418;
  let i419: State330 = State330::Option332(70.92993772026846, 8933, head335);
  match i419 {
    State330::Point331(_, _, _) => ();
    State330::Option332(_, _, _) => ();
    State330::Point333 => ();
    State330::Data334 => ();
  };
  let _ = i419;
  let result420: Int = head27(value88, 3);
  let _ = print_int(result420);
  let data421: Double = status97(());
  let _ = data421;
  let elem422: Bool = value128((), top26);
  let _ = elem422;
  let sum423: Double = info169(1, ());
  let _ = sum423;
  let tail424: Double = data197();
  let _ = tail424;
  let _ = result216();
  let first425: Bool = value244(value244(next285));
  let _ = first425;
  let node426: Bool = count291();
  let _ = node426;
  let next427: Double = head351((), next285);
  let _ = next427;
}


