struct Tree1 {
  y2: (Unit, Int, Unit);
  data3: Unit;
}

struct Option4 {
  item5: (Int, Int, Int);
  item6: (Unit, Unit, Int, Unit);
  max7: Array[Int];
  i8: Int;
}

struct Point9 {
  head10: Array[Unit];
}

struct Instance11 {
  y12: Unit;
}

struct Container13 {
  temp14: Bool;
  bottom15: Double;
  index16: Bool;
}

enum Matrix17 {
  Queue18(Array[Unit]);
  Wrapper19(Array[Unit]);
  Complex20(Array[Unit], Double, Bool);
}

enum Option21 {
  Node22(Array[Int]);
}

enum Vector23 {
  Queue24(Double, Bool);
}

enum Entry25 {
  Point26(Double);
}

enum Instance27 {
  Node28(Bool, Array[Bool]);
  Vector29(Double, Unit, Bool);
  Queue30(Array[Unit]);
  Buffer31;
}

let max32: Double = 506.25595804143666 / 797.2091014524381;

enum Vector33 {
  Context34;
  Option35;
  Value36(Array[Unit]);
}

fn result37() -> Bool {
  let b38: Double = 918.0345219645242;
  let sum39 = ();
  let temp40: Array[(Bool, Bool)] = [(true, true), (true, true), (true, false), (false, true), (true, true), (false, false), (true, false), (false, true)];
  let min41 = b38 * 53.0194345040218;
  let (_, data42, _): (Double, Double, Bool) = (782.1887853981551, 146.58241096071646, false);
  let top43: Array[Array[Double]] = Array::make(8, Array::make(9, 677.2014896772882));
  let tail44: Double = 707.0091214752597;
  let result45 = Array::make(7, Array::make(9, false));
  let mut a46 = [(), (), sum39, (), (), (), ()];
  a46 = a46;
  a46 = Array::make(6, sum39);
  let current47: Bool = true && false;
  let value48: Double = 499.921956812452 % 416.1829991027749;
  let result49: Double = 94.78078329171069;
  let z50: Bool = true && current47;
  a46 = a46;
  let flag51: Double = 749.102532233634;
  a46 = Array::make(10, sum39);
  return current47 && current47;
  let c52: Bool = true;
  a46 = a46;
  a46 = Array::make(7, sum39);
  let sum53: Tree1 = Tree1::{y2: ((), 294, ()), data3: ()};
  let _ = sum53.y2;
  let _ = sum53.data3;
  let _ = sum53;
  let status54: Option4 = Option4::{item5: (55, 58292, 910), item6: ((), (), 5, ()), max7: [1, 1, 1, 0, 1, 6, -1, 95582, 897], i8: 89};
  let _ = status54.item5;
  let _ = status54.item6;
  let _ = status54.max7;
  let _ = print_int(status54.i8);
  let _ = status54;
  let a55: Point9 = Point9::{head10: Array::make(7, ())};
  let _ = a55.head10;
  let _ = a55;
  let info56: Instance11 = Instance11::{y12: ()};
  let _ = info56.y12;
  let _ = info56;
  let z57: Container13 = Container13::{temp14: true, bottom15: max32, index16: false};
  let _ = z57.temp14;
  let _ = z57.bottom15;
  let _ = z57.index16;
  let _ = z57;
  let k58: Matrix17 = Matrix17::Complex20(Array::make(9, ()), max32, true);
  match k58 {
    Matrix17::Queue18(_) => ();
    Matrix17::Wrapper19(_) => ();
    Matrix17::Complex20(_, _, _) => ();
  };
  let _ = k58;
  let min59: Option21 = Option21::Node22(Array::make(7, 10088));
  match min59 {
    Option21::Node22(_) => ();
  };
  let _ = min59;
  let left60: Vector23 = Vector23::Queue24(313.17057747572176, true);
  match left60 {
    Vector23::Queue24(_, _) => ();
  };
  let _ = left60;
  let last61: Entry25 = Entry25::Point26(412.36455580815635);
  match last61 {
    Entry25::Point26(_) => ();
  };
  let _ = last61;
  let data62: Instance27 = Instance27::Node28(false, [false, true, false, false, true, false]);
  match data62 {
    Instance27::Node28(_, _) => ();
    Instance27::Vector29(_, _, _) => ();
    Instance27::Queue30(_) => ();
    Instance27::Buffer31 => ();
  };
  let _ = data62;
  let temp63: Vector33 = Vector33::Context34;
  match temp63 {
    Vector33::Context34 => ();
    Vector33::Option35 => ();
    Vector33::Value36(_) => ();
  };
  let _ = temp63;
  9 >= -1
}

fn status64(a65: Unit, sum66: Int) -> Unit {
  let last67: Bool = false || true;
  let item68: Double = 164.35182829040906 * 750.3285909224611;
  let node69 = true;
  let first70: (Unit, Double, Double) = (a65, item68, 157.49778133274495);
  let b71: Option4 = Option4::{item5: (9, 7, 1), item6: ((), a65, sum66, ()), max7: Array::make(7, sum66), i8: sum66};
  let left72: Double = 249.85456890054937;
  let mut i73: Bool = node69;
  i73 = true;
  let mut a74: Double = 292.049984716771;
  a74 = max32;
  let y75: Unit = ();
  let sum76 = (y75, false);
  let mut right77: Array[(Unit, Unit, Int)] = Array::make(6, (a65, (), 1));
  right77 = right77;
  let mut value78: Double = 764.4360419787295;
  value78 = item68;
  let mut a79: Unit = ();
  a79 = a79;
  i73 = true;
  a74 = item68;
  a74 = max32;
  let _ = {
    let mut sum80: Int = 0;
    while sum80 < 3 {
    match -1 {
    4 => ();
    _ => ();
  };
    if node69 {
    a79
  } else {
    y75
  };
    sum80 = sum80 + 1;
  }
  };
  let b81: Double = 488.0741559872088;
  let current82: Tree1 = Tree1::{y2: ((), 9, ()), data3: ()};
  let _ = current82.y2;
  let _ = current82.data3;
  let _ = current82;
  let temp83: Option4 = Option4::{item5: (67318, -1, 20066), item6: ((), (), sum66, ()), max7: Array::make(6, 89635), i8: 3};
  let _ = temp83.item5;
  let _ = temp83.item6;
  let _ = temp83.max7;
  let _ = print_int(temp83.i8);
  let _ = temp83;
  let elem84: Point9 = Point9::{head10: [a65, a65, (), a65, (), (), a65]};
  let _ = elem84.head10;
  let _ = elem84;
  let node85: Instance11 = Instance11::{y12: a65};
  let _ = node85.y12;
  let _ = node85;
  let info86: Container13 = Container13::{temp14: true, bottom15: 423.0071919876049, index16: false};
  let _ = info86.temp14;
  let _ = info86.bottom15;
  let _ = info86.index16;
  let _ = info86;
  let next87: Matrix17 = Matrix17::Wrapper19([(), (), a65, (), a65, a65, (), (), a65, ()]);
  match next87 {
    Matrix17::Queue18(_) => ();
    Matrix17::Wrapper19(_) => ();
    Matrix17::Complex20(_, _, _) => ();
  };
  let _ = next87;
  let max88: Option21 = Option21::Node22(Array::make(7, 886));
  match max88 {
    Option21::Node22(_) => ();
  };
  let _ = max88;
  let node89: Vector23 = Vector23::Queue24(max32, false);
  match node89 {
    Vector23::Queue24(_, _) => ();
  };
  let _ = node89;
  let count90: Entry25 = Entry25::Point26(490.4573538365914);
  match count90 {
    Entry25::Point26(_) => ();
  };
  let _ = count90;
  let max91: Instance27 = Instance27::Node28(false, [true, true, true, false, false, true, true, true]);
  match max91 {
    Instance27::Node28(_, _) => ();
    Instance27::Vector29(_, _, _) => ();
    Instance27::Queue30(_) => ();
    Instance27::Buffer31 => ();
  };
  let _ = max91;
  let min92: Vector33 = Vector33::Context34;
  match min92 {
    Vector33::Context34 => ();
    Vector33::Option35 => ();
    Vector33::Value36(_) => ();
  };
  let _ = min92;
  let z93: Bool = result37();
  let _ = z93;
  let _ = a65;
  let _ = print_int(sum66);
}

let tail94: Int = 592;

fn x95() -> Bool {
  let mut sum96: Int = tail94;
  sum96 = 8145;
  sum96 = tail94;
  let c97: Bool = false || false;
  match false {
    true => ();
    false => status64((), 33675);
  };
  sum96 = 1;
  sum96 = 1;
  let mut max98 = max32 + 447.72385666351687;
  max98 = 913.7618073140383;
  let info99: Int = 693;
  let (_, count100, current101) = (false, false, status64((), info99));
  let first102: Bool = info99 != 89953;
  if first102 {
    current101
  } else {
    ()
  };
  let mut temp103: Array[Int] = [-1, 52048, 1, 21835, -1, 78212, 5];
  temp103 = [tail94, sum96, 9, 4, info99, info99, -1, 5, 7, -1];
  let a104 = result37();
  temp103 = Array::make(8, 53055);
  let temp105: Unit = ();
  let mut next106: Bool = !count100;
  next106 = true;
  let _ = {
    let mut next107: Int = 0;
    while next107 < 1 {
    let _ = temp105;
    next107 = next107 + 1;
  }
  };
  let (item108, _, _) = (false, tail94, a104);
  let count109: Tree1 = Tree1::{y2: ((), 1, current101), data3: ()};
  let (_, status110) = (info99, count100);
  let (info111, bottom112, _): (Int, Bool, Double) = (2, true, max32);
  max98 = 882.1660294959269;
  let x113: Unit = ();
  if false {
    ()
  } else {
    ()
  };
  let last114 = info111;
  let next115 = 786.4008327622039 - max32;
  sum96 = 1;
  let bottom116 = Array::make(10, status64((), 994));
  let mut prev117: Unit = ();
  prev117 = temp105;
  let info118 = ();
  let info119: Bool = true;
  let status120: Tree1 = Tree1::{y2: ((), 627, ()), data3: ()};
  let _ = status120.y2;
  let _ = status120.data3;
  let _ = status120;
  let x121: Option4 = Option4::{item5: (-1, tail94, tail94), item6: ((), (), tail94, ()), max7: Array::make(9, 20517), i8: tail94};
  let _ = x121.item5;
  let _ = x121.item6;
  let _ = x121.max7;
  let _ = print_int(x121.i8);
  let _ = x121;
  let left122: Point9 = Point9::{head10: Array::make(10, ())};
  let _ = left122.head10;
  let _ = left122;
  let min123: Instance11 = Instance11::{y12: ()};
  let _ = min123.y12;
  let _ = min123;
  let tail124: Container13 = Container13::{temp14: true, bottom15: 338.1473669240352, index16: true};
  let _ = tail124.temp14;
  let _ = tail124.bottom15;
  let _ = tail124.index16;
  let _ = tail124;
  let right125: Matrix17 = Matrix17::Complex20([status64((), tail94), (), (), status64((), 336), (), ()], max32, false);
  match right125 {
    Matrix17::Queue18(_) => ();
    Matrix17::Wrapper19(_) => ();
    Matrix17::Complex20(_, _, _) => ();
  };
  let _ = right125;
  let top126: Option21 = Option21::Node22([0, 80731, 22141, tail94, tail94, 1]);
  match top126 {
    Option21::Node22(_) => ();
  };
  let _ = top126;
  let index127: Vector23 = Vector23::Queue24(539.2002045411419, true);
  match index127 {
    Vector23::Queue24(_, _) => ();
  };
  let _ = index127;
  let first128: Entry25 = Entry25::Point26(max32);
  match first128 {
    Entry25::Point26(_) => ();
  };
  let _ = first128;
  let b129: Instance27 = Instance27::Vector29(max32, (), true);
  match b129 {
    Instance27::Node28(_, _) => ();
    Instance27::Vector29(_, _, _) => ();
    Instance27::Queue30(_) => ();
    Instance27::Buffer31 => ();
  };
  let _ = b129;
  let flag130: Vector33 = Vector33::Option35;
  match flag130 {
    Vector33::Context34 => ();
    Vector33::Option35 => ();
    Vector33::Value36(_) => ();
  };
  let _ = flag130;
  let i131: Bool = result37();
  let _ = i131;
  let _ = status64((), 7);
  false && false
}

let top132: Double = if true {
    max32
  } else {
    max32
  };

let temp133: (Double, Bool, Double) = (max32, true, top132);

enum Option134 {
  Instance135;
  Cache136(Bool, Double, Bool);
  Point137(Int, Array[Unit], Double);
}

enum Vector138 {
  List139(Double, Bool);
  Structure140;
  Context141(Int);
}

let i142: Unit = if false {
    ()
  } else {
    ()
  };

struct Data143 {
  node144: Int;
  left145: Bool;
  top146: Bool;
  min147: (Double, Unit);
}

enum Stack148 {
  Element149(Double, Int, Bool);
  Tree150(Unit, Array[Double], Unit);
}

struct Value151 {
  y152: Array[Int];
  item153: Unit;
  data154: (Double, Double, Bool, Int);
}

let last155: Int = tail94;

let result156: Double = 650.0760743557246;

struct Structure157 {
  node158: Array[Int];
  b159: Array[Unit];
}

let y160: Bool = true;

fn min161(b162: Bool, index163: Bool) -> Double {
  let result164 = 63.8950475065827;
  if true {
    i142
  } else {
    ()
  };
  let elem165: Double = 814.5053383444622;
  let sum166: Int = tail94;
  let c167: Bool = 263.82546933695437 <= result156;
  let data168: (Bool, Bool) = (true, true);
  let value169: Tree1 = Tree1::{y2: ((), tail94, ()), data3: i142};
  let _ = value169.y2;
  let _ = value169.data3;
  let _ = value169;
  let i170: Option4 = Option4::{item5: (last155, tail94, tail94), item6: ((), i142, 93399, ()), max7: Array::make(8, 95544), i8: last155};
  let _ = i170.item5;
  let _ = i170.item6;
  let _ = i170.max7;
  let _ = print_int(i170.i8);
  let _ = i170;
  let temp171: Point9 = Point9::{head10: [(), (), (), (), (), i142, i142, (), i142, i142]};
  let _ = temp171.head10;
  let _ = temp171;
  let x172: Instance11 = Instance11::{y12: i142};
  let _ = x172.y12;
  let _ = x172;
  let item173: Container13 = Container13::{temp14: false, bottom15: max32, index16: true};
  let _ = item173.temp14;
  let _ = item173.bottom15;
  let _ = item173.index16;
  let _ = item173;
  let item174: Data143 = Data143::{node144: -1, left145: false, top146: y160, min147: (460.4852960891237, i142)};
  let _ = print_int(item174.node144);
  let _ = item174.left145;
  let _ = item174.top146;
  let _ = item174.min147;
  let _ = item174;
  let sum175: Value151 = Value151::{y152: [5, -1, 41656, 347, last155, -1, 268, 174, 95145], item153: (), data154: (772.9447343862286, result156, false, last155)};
  let _ = sum175.y152;
  let _ = sum175.item153;
  let _ = sum175.data154;
  let _ = sum175;
  let value176: Structure157 = Structure157::{node158: [0, tail94, last155, 80513, tail94, 74018, 5, tail94, 72729], b159: Array::make(8, i142)};
  let _ = value176.node158;
  let _ = value176.b159;
  let _ = value176;
  let i177: Matrix17 = Matrix17::Complex20(Array::make(7, i142), 219.60799447359557, false);
  match i177 {
    Matrix17::Queue18(_) => ();
    Matrix17::Wrapper19(_) => ();
    Matrix17::Complex20(_, _, _) => ();
  };
  let _ = i177;
  let node178: Option21 = Option21::Node22(Array::make(6, 878));
  match node178 {
    Option21::Node22(_) => ();
  };
  let _ = node178;
  let count179: Vector23 = Vector23::Queue24(1.8729594784618886, true);
  match count179 {
    Vector23::Queue24(_, _) => ();
  };
  let _ = count179;
  let result180: Entry25 = Entry25::Point26(top132);
  match result180 {
    Entry25::Point26(_) => ();
  };
  let _ = result180;
  let bottom181: Instance27 = Instance27::Vector29(924.4048977612354, i142, true);
  match bottom181 {
    Instance27::Node28(_, _) => ();
    Instance27::Vector29(_, _, _) => ();
    Instance27::Queue30(_) => ();
    Instance27::Buffer31 => ();
  };
  let _ = bottom181;
  let item182: Vector33 = Vector33::Context34;
  match item182 {
    Vector33::Context34 => ();
    Vector33::Option35 => ();
    Vector33::Value36(_) => ();
  };
  let _ = item182;
  let item183: Option134 = Option134::Point137(9, Array::make(7, i142), 579.6204231849915);
  match item183 {
    Option134::Instance135 => ();
    Option134::Cache136(_, _, _) => ();
    Option134::Point137(_, _, _) => ();
  };
  let _ = item183;
  let prev184: Vector138 = Vector138::Structure140;
  match prev184 {
    Vector138::List139(_, _) => ();
    Vector138::Structure140 => ();
    Vector138::Context141(_) => ();
  };
  let _ = prev184;
  let top185: Stack148 = Stack148::Tree150((), [948.5526203522264, result156, 746.848682355081, result156, 702.4841708318066, 244.91815138083706, 570.8757219621048, 622.363347440414, 713.4413341946942], ());
  match top185 {
    Stack148::Element149(_, _, _) => ();
    Stack148::Tree150(_, _, _) => ();
  };
  let _ = top185;
  let first186: Bool = result37();
  let _ = first186;
  let _ = status64(i142, tail94);
  let min187: Bool = x95();
  let _ = min187;
  let _ = b162;
  let _ = index163;
  156.2259352088673 + 634.9785259753357
}

let left188: Int = last155;

struct Data189 {
  temp190: Unit;
  temp191: Double;
  next192: Bool;
  first193: Array[Int];
}

let count194: Double = 63.94950694096391;

struct Stack195 {
  first196: Double;
  z197: Array[Bool];
  max198: (Bool, Unit, Int, Int);
  k199: (Unit, Int);
}

let top200: Array[Array[Double]] = [[count194, top132, result156, 73.121347816687, 342.1378677279282, 957.705037122755, max32, 228.32382794056704, 992.2165139008637, max32], Array::make(6, result156), [904.4488284221164, 954.5623551438196, min161(false, true), count194, 443.92909864826225, 675.5225004348642, 881.6625812637039, 154.93179746009454, 389.55196629927127, count194], Array::make(6, top132), [608.0754181093406, 179.55535026646797, top132, 822.5192449957473, 536.3649887148174, 578.0722865301025, max32, result156, result156], [791.9262446109352, 688.3387307705211, 469.2065863483413, result156, 709.1099394044686, min161(false, y160), top132], Array::make(8, 939.0876272914959), [942.1237719037348, result156, top132, top132, 856.2995132815122, max32, 825.3116033630155, 822.1192730055228, 14.761260442348378], [644.0459137528438, 750.2187733378273, result156, count194, 8.089028298933654, max32, 846.6700316263485, min161(y160, y160)]];

enum Queue201 {
  Structure202;
  Vector203;
  Matrix204;
}

let count205: Unit = ();

let result206: (Int, Int, Bool) = (left188, 1, y160);

struct Data207 {
  sum208: Double;
  temp209: Int;
  y210: Int;
  a211: (Int, Int, Unit);
}

struct Queue212 {
  info213: (Unit, Double);
}

let elem214: Int = 9;

fn status215(max216: Double, i217: Int) -> Double {
  let node218: Int = 77400 / tail94;
  let item219: Tree1 = Tree1::{y2: (i142, 7, ()), data3: i142};
  let _ = item219.y2;
  let _ = item219.data3;
  let _ = item219;
  let value220: Option4 = Option4::{item5: (89052, elem214, 734), item6: (count205, (), last155, i142), max7: Array::make(6, -1), i8: elem214};
  let _ = value220.item5;
  let _ = value220.item6;
  let _ = value220.max7;
  let _ = print_int(value220.i8);
  let _ = value220;
  let a221: Point9 = Point9::{head10: [(), (), (), i142, status64((), 211), (), (), i142, (), i142]};
  let _ = a221.head10;
  let _ = a221;
  let tail222: Instance11 = Instance11::{y12: i142};
  let _ = tail222.y12;
  let _ = tail222;
  let x223: Container13 = Container13::{temp14: true, bottom15: 305.8580785206392, index16: false};
  let _ = x223.temp14;
  let _ = x223.bottom15;
  let _ = x223.index16;
  let _ = x223;
  let elem224: Data143 = Data143::{node144: 83700, left145: y160, top146: false, min147: (max216, ())};
  let _ = print_int(elem224.node144);
  let _ = elem224.left145;
  let _ = elem224.top146;
  let _ = elem224.min147;
  let _ = elem224;
  let current225: Value151 = Value151::{y152: [elem214, elem214, 47443, 1, tail94, left188, 18493, 6, 26757, last155], item153: count205, data154: (max216, 235.71988869669636, false, tail94)};
  let _ = current225.y152;
  let _ = current225.item153;
  let _ = current225.data154;
  let _ = current225;
  let a226: Structure157 = Structure157::{node158: Array::make(6, 568), b159: Array::make(6, ())};
  let _ = a226.node158;
  let _ = a226.b159;
  let _ = a226;
  let tail227: Data189 = Data189::{temp190: (), temp191: top132, next192: false, first193: [tail94, -1, 18818, 664, i217, 878, 269]};
  let _ = tail227.temp190;
  let _ = tail227.temp191;
  let _ = tail227.next192;
  let _ = tail227.first193;
  let _ = tail227;
  let sum228: Stack195 = Stack195::{first196: 527.0934357765783, z197: [true, true, false, y160, y160, true, y160, true], max198: (y160, count205, 1, 5), k199: ((), last155)};
  let _ = sum228.first196;
  let _ = sum228.z197;
  let _ = sum228.max198;
  let _ = sum228.k199;
  let _ = sum228;
  let first229: Data207 = Data207::{sum208: 182.76070272676148, temp209: 8, y210: 9, a211: (1, 68592, count205)};
  let _ = first229.sum208;
  let _ = print_int(first229.temp209);
  let _ = print_int(first229.y210);
  let _ = first229.a211;
  let _ = first229;
  let value230: Queue212 = Queue212::{info213: (count205, 777.819050044405)};
  let _ = value230.info213;
  let _ = value230;
  let current231: Matrix17 = Matrix17::Complex20(Array::make(10, ()), 676.2304618796301, y160);
  match current231 {
    Matrix17::Queue18(_) => ();
    Matrix17::Wrapper19(_) => ();
    Matrix17::Complex20(_, _, _) => ();
  };
  let _ = current231;
  let z232: Option21 = Option21::Node22([4, left188, -1, 48313, 2, elem214, 87747, 9, i217, last155]);
  match z232 {
    Option21::Node22(_) => ();
  };
  let _ = z232;
  let first233: Vector23 = Vector23::Queue24(122.22909131331383, false);
  match first233 {
    Vector23::Queue24(_, _) => ();
  };
  let _ = first233;
  let c234: Entry25 = Entry25::Point26(327.0191437077901);
  match c234 {
    Entry25::Point26(_) => ();
  };
  let _ = c234;
  let current235: Instance27 = Instance27::Queue30([(), (), count205, count205, count205, ()]);
  match current235 {
    Instance27::Node28(_, _) => ();
    Instance27::Vector29(_, _, _) => ();
    Instance27::Queue30(_) => ();
    Instance27::Buffer31 => ();
  };
  let _ = current235;
  let index236: Vector33 = Vector33::Context34;
  match index236 {
    Vector33::Context34 => ();
    Vector33::Option35 => ();
    Vector33::Value36(_) => ();
  };
  let _ = index236;
  let next237: Option134 = Option134::Instance135;
  match next237 {
    Option134::Instance135 => ();
    Option134::Cache136(_, _, _) => ();
    Option134::Point137(_, _, _) => ();
  };
  let _ = next237;
  let a238: Vector138 = Vector138::Structure140;
  match a238 {
    Vector138::List139(_, _) => ();
    Vector138::Structure140 => ();
    Vector138::Context141(_) => ();
  };
  let _ = a238;
  let next239: Stack148 = Stack148::Tree150((), [864.2912496077921, 417.10046099652453, count194, 366.3370086015369, 484.694616249406, 413.65364870807076, 17.093211604569113], ());
  match next239 {
    Stack148::Element149(_, _, _) => ();
    Stack148::Tree150(_, _, _) => ();
  };
  let _ = next239;
  let b240: Queue201 = Queue201::Structure202;
  match b240 {
    Queue201::Structure202 => ();
    Queue201::Vector203 => ();
    Queue201::Matrix204 => ();
  };
  let _ = b240;
  let elem241: Bool = result37();
  let _ = elem241;
  let _ = status64((), -1);
  let c242: Bool = x95();
  let _ = c242;
  let temp243: Double = min161(y160, true);
  let _ = temp243;
  let _ = max216;
  let _ = print_int(i217);
  444.2753549584029
}

fn first244() -> Bool {
  let value245: Unit = (());
  let left246: Tree1 = Tree1::{y2: ((), 54359, ()), data3: count205};
  let _ = left246.y2;
  let _ = left246.data3;
  let _ = left246;
  let min247: Option4 = Option4::{item5: (tail94, 5515, elem214), item6: (count205, (), 7, ()), max7: [left188, tail94, tail94, tail94, left188, 23963, 36, 6009, 1], i8: 365};
  let _ = min247.item5;
  let _ = min247.item6;
  let _ = min247.max7;
  let _ = print_int(min247.i8);
  let _ = min247;
  let x248: Point9 = Point9::{head10: [(), count205, (), (), count205, i142, ()]};
  let _ = x248.head10;
  let _ = x248;
  let x249: Instance11 = Instance11::{y12: ()};
  let _ = x249.y12;
  let _ = x249;
  let current250: Container13 = Container13::{temp14: true, bottom15: count194, index16: true};
  let _ = current250.temp14;
  let _ = current250.bottom15;
  let _ = current250.index16;
  let _ = current250;
  let count251: Data143 = Data143::{node144: 93010, left145: false, top146: false, min147: (max32, ())};
  let _ = print_int(count251.node144);
  let _ = count251.left145;
  let _ = count251.top146;
  let _ = count251.min147;
  let _ = count251;
  let k252: Value151 = Value151::{y152: [left188, left188, 746, left188, tail94, -1, tail94, 99984, last155], item153: i142, data154: (count194, 643.8725341835735, y160, left188)};
  let _ = k252.y152;
  let _ = k252.item153;
  let _ = k252.data154;
  let _ = k252;
  let result253: Structure157 = Structure157::{node158: Array::make(9, 284), b159: [(), (), count205, count205, (), ()]};
  let _ = result253.node158;
  let _ = result253.b159;
  let _ = result253;
  let b254: Data189 = Data189::{temp190: (), temp191: 113.19122188849707, next192: true, first193: Array::make(7, 806)};
  let _ = b254.temp190;
  let _ = b254.temp191;
  let _ = b254.next192;
  let _ = b254.first193;
  let _ = b254;
  let b255: Stack195 = Stack195::{first196: result156, z197: [y160, false, y160, y160, true, y160, y160], max198: (true, count205, 57455, elem214), k199: ((), elem214)};
  let _ = b255.first196;
  let _ = b255.z197;
  let _ = b255.max198;
  let _ = b255.k199;
  let _ = b255;
  let b256: Data207 = Data207::{sum208: result156, temp209: left188, y210: tail94, a211: (left188, last155, ())};
  let _ = b256.sum208;
  let _ = print_int(b256.temp209);
  let _ = print_int(b256.y210);
  let _ = b256.a211;
  let _ = b256;
  let sum257: Queue212 = Queue212::{info213: (count205, 241.07814039045405)};
  let _ = sum257.info213;
  let _ = sum257;
  let tail258: Matrix17 = Matrix17::Wrapper19(Array::make(8, ()));
  match tail258 {
    Matrix17::Queue18(_) => ();
    Matrix17::Wrapper19(_) => ();
    Matrix17::Complex20(_, _, _) => ();
  };
  let _ = tail258;
  let item259: Option21 = Option21::Node22([792, 8, 335, 1, last155, 92422, 38633, 8, 620]);
  match item259 {
    Option21::Node22(_) => ();
  };
  let _ = item259;
  let sum260: Vector23 = Vector23::Queue24(949.7548750414763, true);
  match sum260 {
    Vector23::Queue24(_, _) => ();
  };
  let _ = sum260;
  let min261: Entry25 = Entry25::Point26(min161(y160, true));
  match min261 {
    Entry25::Point26(_) => ();
  };
  let _ = min261;
  let k262: Instance27 = Instance27::Buffer31;
  match k262 {
    Instance27::Node28(_, _) => ();
    Instance27::Vector29(_, _, _) => ();
    Instance27::Queue30(_) => ();
    Instance27::Buffer31 => ();
  };
  let _ = k262;
  let node263: Vector33 = Vector33::Value36([i142, count205, count205, count205, (), i142]);
  match node263 {
    Vector33::Context34 => ();
    Vector33::Option35 => ();
    Vector33::Value36(_) => ();
  };
  let _ = node263;
  let left264: Option134 = Option134::Cache136(y160, 314.5207658553034, true);
  match left264 {
    Option134::Instance135 => ();
    Option134::Cache136(_, _, _) => ();
    Option134::Point137(_, _, _) => ();
  };
  let _ = left264;
  let elem265: Vector138 = Vector138::Context141(923);
  match elem265 {
    Vector138::List139(_, _) => ();
    Vector138::Structure140 => ();
    Vector138::Context141(_) => ();
  };
  let _ = elem265;
  let data266: Stack148 = Stack148::Tree150(count205, Array::make(10, 39.9095376316384), ());
  match data266 {
    Stack148::Element149(_, _, _) => ();
    Stack148::Tree150(_, _, _) => ();
  };
  let _ = data266;
  let last267: Queue201 = Queue201::Structure202;
  match last267 {
    Queue201::Structure202 => ();
    Queue201::Vector203 => ();
    Queue201::Matrix204 => ();
  };
  let _ = last267;
  let k268: Bool = result37();
  let _ = k268;
  let _ = status64((), tail94);
  let left269: Bool = x95();
  let _ = left269;
  let status270: Double = min161(true, true);
  let _ = status270;
  let bottom271: Double = status215(max32, 45);
  let _ = bottom271;
  false
}

let prev272: Double = 954.5319952894667;

struct Item273 {
  status274: Double;
  x275: Bool;
  b276: Double;
}

enum Item277 {
  Result278(Bool, Int);
  Data279;
}

let temp280: Array[Int] = [380, tail94, 843, left188, 15872, -1, 25, 91776, tail94, 6];

struct Vector281 {
  node282: Bool;
  i283: Int;
  value284: Int;
  info285: Int;
}

struct Vector286 {
  value287: Bool;
  k288: Array[Unit];
}

let elem289: Bool = 1 > 487;

fn data290() -> Double {
  let mut prev291: Int = 5;
  prev291 = 19411;
  let index292: Tree1 = Tree1::{y2: (count205, 40290, ()), data3: ()};
  let _ = index292.y2;
  let _ = index292.data3;
  let _ = index292;
  let result293: Option4 = Option4::{item5: (802, 256, 1), item6: ((), count205, 878, ()), max7: [last155, 956, 41321, 106, tail94, 2, 1, 1, last155], i8: -1};
  let _ = result293.item5;
  let _ = result293.item6;
  let _ = result293.max7;
  let _ = print_int(result293.i8);
  let _ = result293;
  let k294: Point9 = Point9::{head10: Array::make(7, ())};
  let _ = k294.head10;
  let _ = k294;
  let y295: Instance11 = Instance11::{y12: ()};
  let _ = y295.y12;
  let _ = y295;
  let sum296: Container13 = Container13::{temp14: true, bottom15: min161(elem289, elem289), index16: elem289};
  let _ = sum296.temp14;
  let _ = sum296.bottom15;
  let _ = sum296.index16;
  let _ = sum296;
  let status297: Data143 = Data143::{node144: 7949, left145: true, top146: true, min147: (53.30547038242739, ())};
  let _ = print_int(status297.node144);
  let _ = status297.left145;
  let _ = status297.top146;
  let _ = status297.min147;
  let _ = status297;
  let c298: Value151 = Value151::{y152: [last155, elem214, last155, elem214, left188, 667, 18089, 8, 68155], item153: i142, data154: (129.97570192343312, 645.6769082664304, elem289, 681)};
  let _ = c298.y152;
  let _ = c298.item153;
  let _ = c298.data154;
  let _ = c298;
  let elem299: Structure157 = Structure157::{node158: Array::make(7, 27148), b159: [(), (), (), (), i142, (), (), ()]};
  let _ = elem299.node158;
  let _ = elem299.b159;
  let _ = elem299;
  let last300: Data189 = Data189::{temp190: (), temp191: 991.6222531987689, next192: false, first193: Array::make(7, 33528)};
  let _ = last300.temp190;
  let _ = last300.temp191;
  let _ = last300.next192;
  let _ = last300.first193;
  let _ = last300;
  let top301: Stack195 = Stack195::{first196: status215(result156, 73228), z197: Array::make(7, false), max198: (false, (), 19020, tail94), k199: (count205, tail94)};
  let _ = top301.first196;
  let _ = top301.z197;
  let _ = top301.max198;
  let _ = top301.k199;
  let _ = top301;
  let first302: Data207 = Data207::{sum208: 109.69488717611287, temp209: 373, y210: elem214, a211: (6394, 5189, i142)};
  let _ = first302.sum208;
  let _ = print_int(first302.temp209);
  let _ = print_int(first302.y210);
  let _ = first302.a211;
  let _ = first302;
  let current303: Queue212 = Queue212::{info213: ((), count194)};
  let _ = current303.info213;
  let _ = current303;
  let target304: Item273 = Item273::{status274: 371.3414475911442, x275: elem289, b276: 374.20942962907554};
  let _ = target304.status274;
  let _ = target304.x275;
  let _ = target304.b276;
  let _ = target304;
  let max305: Vector281 = Vector281::{node282: true, i283: last155, value284: 624, info285: elem214};
  let _ = max305.node282;
  let _ = print_int(max305.i283);
  let _ = print_int(max305.value284);
  let _ = print_int(max305.info285);
  let _ = max305;
  let j306: Vector286 = Vector286::{value287: false, k288: Array::make(9, ())};
  let _ = j306.value287;
  let _ = j306.k288;
  let _ = j306;
  let top307: Matrix17 = Matrix17::Wrapper19([count205, count205, (), count205, (), ()]);
  match top307 {
    Matrix17::Queue18(_) => ();
    Matrix17::Wrapper19(_) => ();
    Matrix17::Complex20(_, _, _) => ();
  };
  let _ = top307;
  let x308: Option21 = Option21::Node22([34199, 0, elem214, elem214, tail94, 1, 4, 1, last155, left188]);
  match x308 {
    Option21::Node22(_) => ();
  };
  let _ = x308;
  let bottom309: Vector23 = Vector23::Queue24(190.69134489834337, false);
  match bottom309 {
    Vector23::Queue24(_, _) => ();
  };
  let _ = bottom309;
  let b310: Entry25 = Entry25::Point26(top132);
  match b310 {
    Entry25::Point26(_) => ();
  };
  let _ = b310;
  let elem311: Instance27 = Instance27::Node28(false, Array::make(10, false));
  match elem311 {
    Instance27::Node28(_, _) => ();
    Instance27::Vector29(_, _, _) => ();
    Instance27::Queue30(_) => ();
    Instance27::Buffer31 => ();
  };
  let _ = elem311;
  let elem312: Vector33 = Vector33::Value36(Array::make(8, ()));
  match elem312 {
    Vector33::Context34 => ();
    Vector33::Option35 => ();
    Vector33::Value36(_) => ();
  };
  let _ = elem312;
  let flag313: Option134 = Option134::Cache136(false, max32, elem289);
  match flag313 {
    Option134::Instance135 => ();
    Option134::Cache136(_, _, _) => ();
    Option134::Point137(_, _, _) => ();
  };
  let _ = flag313;
  let bottom314: Vector138 = Vector138::List139(763.1712197055363, true);
  match bottom314 {
    Vector138::List139(_, _) => ();
    Vector138::Structure140 => ();
    Vector138::Context141(_) => ();
  };
  let _ = bottom314;
  let status315: Stack148 = Stack148::Element149(490.329215260991, -1, true);
  match status315 {
    Stack148::Element149(_, _, _) => ();
    Stack148::Tree150(_, _, _) => ();
  };
  let _ = status315;
  let z316: Queue201 = Queue201::Matrix204;
  match z316 {
    Queue201::Structure202 => ();
    Queue201::Vector203 => ();
    Queue201::Matrix204 => ();
  };
  let _ = z316;
  let target317: Item277 = Item277::Result278(true, last155);
  match target317 {
    Item277::Result278(_, _) => ();
    Item277::Data279 => ();
  };
  let _ = target317;
  let bottom318: Bool = result37();
  let _ = bottom318;
  let _ = status64((), last155);
  let result319: Bool = x95();
  let _ = result319;
  let index320: Double = min161(y160, false);
  let _ = index320;
  let right321: Double = status215(851.3538495958468, -1);
  let _ = right321;
  let x322: Bool = first244();
  let _ = x322;
  117.96695054996597
}

let c323: Bool = false || true;

enum Point324 {
  Value325(Int);
  Buffer326(Array[Double], Int);
  Complex327;
}

let node328: Unit = status64((), tail94);

let b329: (Double, Unit) = (result156, ());

struct Result330 {
  value331: Int;
}

fn k332() -> Double {
  let mut elem333 = tail94;
  elem333 = 39789;
  let b334: Tree1 = Tree1::{y2: (node328, 9, ()), data3: ()};
  let _ = b334.y2;
  let _ = b334.data3;
  let _ = b334;
  let prev335: Option4 = Option4::{item5: (1, 1, last155), item6: (status64((), -1), (), elem214, ()), max7: [3, left188, -1, 3, last155, 1], i8: left188};
  let _ = prev335.item5;
  let _ = prev335.item6;
  let _ = prev335.max7;
  let _ = print_int(prev335.i8);
  let _ = prev335;
  let value336: Point9 = Point9::{head10: [(), (), (), (), (), i142, (), ()]};
  let _ = value336.head10;
  let _ = value336;
  let max337: Instance11 = Instance11::{y12: ()};
  let _ = max337.y12;
  let _ = max337;
  let sum338: Container13 = Container13::{temp14: c323, bottom15: 71.95401812885083, index16: true};
  let _ = sum338.temp14;
  let _ = sum338.bottom15;
  let _ = sum338.index16;
  let _ = sum338;
  let i339: Data143 = Data143::{node144: 674, left145: false, top146: true, min147: (result156, ())};
  let _ = print_int(i339.node144);
  let _ = i339.left145;
  let _ = i339.top146;
  let _ = i339.min147;
  let _ = i339;
  let right340: Value151 = Value151::{y152: temp280, item153: count205, data154: (prev272, 366.4303700852143, c323, left188)};
  let _ = right340.y152;
  let _ = right340.item153;
  let _ = right340.data154;
  let _ = right340;
  let next341: Structure157 = Structure157::{node158: Array::make(6, 451), b159: Array::make(8, ())};
  let _ = next341.node158;
  let _ = next341.b159;
  let _ = next341;
  let x342: Data189 = Data189::{temp190: count205, temp191: 247.54270868102546, next192: c323, first193: temp280};
  let _ = x342.temp190;
  let _ = x342.temp191;
  let _ = x342.next192;
  let _ = x342.first193;
  let _ = x342;
  let current343: Stack195 = Stack195::{first196: max32, z197: [true, false, true, elem289, true, true, y160, elem289, x95(), false], max198: (true, count205, tail94, 681), k199: ((), left188)};
  let _ = current343.first196;
  let _ = current343.z197;
  let _ = current343.max198;
  let _ = current343.k199;
  let _ = current343;
  let data344: Data207 = Data207::{sum208: 566.8612169972923, temp209: 528, y210: 500, a211: (-1, tail94, ())};
  let _ = data344.sum208;
  let _ = print_int(data344.temp209);
  let _ = print_int(data344.y210);
  let _ = data344.a211;
  let _ = data344;
  let x345: Queue212 = Queue212::{info213: ((), 297.18336116734747)};
  let _ = x345.info213;
  let _ = x345;
  let top346: Item273 = Item273::{status274: 150.20445868786146, x275: elem289, b276: max32};
  let _ = top346.status274;
  let _ = top346.x275;
  let _ = top346.b276;
  let _ = top346;
  let temp347: Vector281 = Vector281::{node282: y160, i283: elem214, value284: 592, info285: 3276};
  let _ = temp347.node282;
  let _ = print_int(temp347.i283);
  let _ = print_int(temp347.value284);
  let _ = print_int(temp347.info285);
  let _ = temp347;
  let current348: Vector286 = Vector286::{value287: true, k288: [count205, (), i142, node328, (), (), ()]};
  let _ = current348.value287;
  let _ = current348.k288;
  let _ = current348;
  let elem349: Result330 = Result330::{value331: -1};
  let _ = print_int(elem349.value331);
  let _ = elem349;
  let k350: Matrix17 = Matrix17::Queue18([i142, (), i142, (), status64((), last155), (), count205, node328, count205, count205]);
  match k350 {
    Matrix17::Queue18(_) => ();
    Matrix17::Wrapper19(_) => ();
    Matrix17::Complex20(_, _, _) => ();
  };
  let _ = k350;
  let count351: Option21 = Option21::Node22(Array::make(9, 25));
  match count351 {
    Option21::Node22(_) => ();
  };
  let _ = count351;
  let info352: Vector23 = Vector23::Queue24(297.90603202544975, true);
  match info352 {
    Vector23::Queue24(_, _) => ();
  };
  let _ = info352;
  let elem353: Entry25 = Entry25::Point26(count194);
  match elem353 {
    Entry25::Point26(_) => ();
  };
  let _ = elem353;
  let tail354: Instance27 = Instance27::Queue30([i142, (), count205, i142, (), (), node328]);
  match tail354 {
    Instance27::Node28(_, _) => ();
    Instance27::Vector29(_, _, _) => ();
    Instance27::Queue30(_) => ();
    Instance27::Buffer31 => ();
  };
  let _ = tail354;
  let top355: Vector33 = Vector33::Context34;
  match top355 {
    Vector33::Context34 => ();
    Vector33::Option35 => ();
    Vector33::Value36(_) => ();
  };
  let _ = top355;
  let value356: Option134 = Option134::Instance135;
  match value356 {
    Option134::Instance135 => ();
    Option134::Cache136(_, _, _) => ();
    Option134::Point137(_, _, _) => ();
  };
  let _ = value356;
  let top357: Vector138 = Vector138::Structure140;
  match top357 {
    Vector138::List139(_, _) => ();
    Vector138::Structure140 => ();
    Vector138::Context141(_) => ();
  };
  let _ = top357;
  let flag358: Stack148 = Stack148::Tree150(status64(i142, last155), [146.66011198365814, 258.55781728688675, 579.6451113698092, max32, 931.3933874787061, min161(false, false), 200.92069449661577, 464.95945524291614, prev272, 539.4413807455145], ());
  match flag358 {
    Stack148::Element149(_, _, _) => ();
    Stack148::Tree150(_, _, _) => ();
  };
  let _ = flag358;
  let b359: Queue201 = Queue201::Vector203;
  match b359 {
    Queue201::Structure202 => ();
    Queue201::Vector203 => ();
    Queue201::Matrix204 => ();
  };
  let _ = b359;
  let data360: Item277 = Item277::Result278(true, 40741);
  match data360 {
    Item277::Result278(_, _) => ();
    Item277::Data279 => ();
  };
  let _ = data360;
  let target361: Point324 = Point324::Complex327;
  match target361 {
    Point324::Value325(_) => ();
    Point324::Buffer326(_, _) => ();
    Point324::Complex327 => ();
  };
  let _ = target361;
  let item362: Bool = result37();
  let _ = item362;
  let _ = status64((), left188);
  let i363: Bool = x95();
  let _ = i363;
  let item364: Double = min161(false, y160);
  let _ = item364;
  let right365: Double = status215(55.0722495239766, 328);
  let _ = right365;
  let j366: Bool = first244();
  let _ = j366;
  let last367: Double = data290();
  let _ = last367;
  956.8545183468023
}

fn prev368(max369: Int, current370: Int) -> Int {
  return 70277;
  let tail371: Tree1 = Tree1::{y2: ((), 61433, ()), data3: ()};
  let _ = tail371.y2;
  let _ = tail371.data3;
  let _ = tail371;
  let sum372: Option4 = Option4::{item5: (elem214, 5, -1), item6: ((), status64((), 909), 61052, ()), max7: [24319, 8933, elem214, last155, 3, 2, elem214], i8: 0};
  let _ = sum372.item5;
  let _ = sum372.item6;
  let _ = sum372.max7;
  let _ = print_int(sum372.i8);
  let _ = sum372;
  let flag373: Point9 = Point9::{head10: Array::make(8, node328)};
  let _ = flag373.head10;
  let _ = flag373;
  let node374: Instance11 = Instance11::{y12: count205};
  let _ = node374.y12;
  let _ = node374;
  let first375: Container13 = Container13::{temp14: false, bottom15: result156, index16: y160};
  let _ = first375.temp14;
  let _ = first375.bottom15;
  let _ = first375.index16;
  let _ = first375;
  let flag376: Data143 = Data143::{node144: 740, left145: elem289, top146: y160, min147: b329};
  let _ = print_int(flag376.node144);
  let _ = flag376.left145;
  let _ = flag376.top146;
  let _ = flag376.min147;
  let _ = flag376;
  let i377: Value151 = Value151::{y152: Array::make(6, tail94), item153: node328, data154: (141.98524575975958, 924.3872783897579, true, current370)};
  let _ = i377.y152;
  let _ = i377.item153;
  let _ = i377.data154;
  let _ = i377;
  let x378: Structure157 = Structure157::{node158: [5, 9, 252, tail94, 445, 33012, left188, 50737, 47452, left188], b159: [node328, count205, (), (), (), status64((), 1)]};
  let _ = x378.node158;
  let _ = x378.b159;
  let _ = x378;
  let status379: Data189 = Data189::{temp190: (), temp191: 252.67703981428323, next192: true, first193: [751, 20, left188, 236, 1, 86375, elem214, 7]};
  let _ = status379.temp190;
  let _ = status379.temp191;
  let _ = status379.next192;
  let _ = status379.first193;
  let _ = status379;
  let elem380: Stack195 = Stack195::{first196: result156, z197: [first244(), false, y160, y160, true, true, y160, true, true, false], max198: (true, (), 578, 0), k199: ((), 17556)};
  let _ = elem380.first196;
  let _ = elem380.z197;
  let _ = elem380.max198;
  let _ = elem380.k199;
  let _ = elem380;
  let top381: Data207 = Data207::{sum208: max32, temp209: current370, y210: current370, a211: (7, 582, ())};
  let _ = top381.sum208;
  let _ = print_int(top381.temp209);
  let _ = print_int(top381.y210);
  let _ = top381.a211;
  let _ = top381;
  let next382: Queue212 = Queue212::{info213: (node328, 977.1549745748576)};
  let _ = next382.info213;
  let _ = next382;
  let min383: Item273 = Item273::{status274: 486.5307768955849, x275: true, b276: 444.0505415854478};
  let _ = min383.status274;
  let _ = min383.x275;
  let _ = min383.b276;
  let _ = min383;
  let value384: Vector281 = Vector281::{node282: c323, i283: left188, value284: 922, info285: -1};
  let _ = value384.node282;
  let _ = print_int(value384.i283);
  let _ = print_int(value384.value284);
  let _ = print_int(value384.info285);
  let _ = value384;
  let z385: Vector286 = Vector286::{value287: true, k288: Array::make(10, ())};
  let _ = z385.value287;
  let _ = z385.k288;
  let _ = z385;
  let current386: Result330 = Result330::{value331: current370};
  let _ = print_int(current386.value331);
  let _ = current386;
  let last387: Matrix17 = Matrix17::Complex20(Array::make(7, ()), max32, true);
  match last387 {
    Matrix17::Queue18(_) => ();
    Matrix17::Wrapper19(_) => ();
    Matrix17::Complex20(_, _, _) => ();
  };
  let _ = last387;
  let first388: Option21 = Option21::Node22([max369, max369, last155, left188, -1, 454, elem214]);
  match first388 {
    Option21::Node22(_) => ();
  };
  let _ = first388;
  let index389: Vector23 = Vector23::Queue24(643.7818022367147, false);
  match index389 {
    Vector23::Queue24(_, _) => ();
  };
  let _ = index389;
  let y390: Entry25 = Entry25::Point26(result156);
  match y390 {
    Entry25::Point26(_) => ();
  };
  let _ = y390;
  let count391: Instance27 = Instance27::Vector29(255.79888955522122, (), true);
  match count391 {
    Instance27::Node28(_, _) => ();
    Instance27::Vector29(_, _, _) => ();
    Instance27::Queue30(_) => ();
    Instance27::Buffer31 => ();
  };
  let _ = count391;
  let next392: Vector33 = Vector33::Option35;
  match next392 {
    Vector33::Context34 => ();
    Vector33::Option35 => ();
    Vector33::Value36(_) => ();
  };
  let _ = next392;
  let count393: Option134 = Option134::Instance135;
  match count393 {
    Option134::Instance135 => ();
    Option134::Cache136(_, _, _) => ();
    Option134::Point137(_, _, _) => ();
  };
  let _ = count393;
  let z394: Vector138 = Vector138::Context141(18);
  match z394 {
    Vector138::List139(_, _) => ();
    Vector138::Structure140 => ();
    Vector138::Context141(_) => ();
  };
  let _ = z394;
  let next395: Stack148 = Stack148::Element149(data290(), last155, false);
  match next395 {
    Stack148::Element149(_, _, _) => ();
    Stack148::Tree150(_, _, _) => ();
  };
  let _ = next395;
  let y396: Queue201 = Queue201::Matrix204;
  match y396 {
    Queue201::Structure202 => ();
    Queue201::Vector203 => ();
    Queue201::Matrix204 => ();
  };
  let _ = y396;
  let item397: Item277 = Item277::Data279;
  match item397 {
    Item277::Result278(_, _) => ();
    Item277::Data279 => ();
  };
  let _ = item397;
  let tail398: Point324 = Point324::Complex327;
  match tail398 {
    Point324::Value325(_) => ();
    Point324::Buffer326(_, _) => ();
    Point324::Complex327 => ();
  };
  let _ = tail398;
  let x399: Bool = result37();
  let _ = x399;
  let _ = status64((), current370);
  let count400: Bool = x95();
  let _ = count400;
  let prev401: Double = min161(c323, true);
  let _ = prev401;
  let a402: Double = status215(93.15826638753887, tail94);
  let _ = a402;
  let prev403: Bool = first244();
  let _ = prev403;
  let data404: Double = data290();
  let _ = data404;
  let count405: Double = k332();
  let _ = count405;
  let _ = print_int(max369);
  let _ = print_int(current370);
  641
}

enum Instance406 {
  Tree407(Double, Bool);
  Node408(Array[Int]);
  Result409;
  Object410(Double, Bool, Bool);
}

let right411: (Double, Double) = (status215(698.0847429306981, 41957), 924.8694274611272);

enum Context412 {
  Entity413(Unit);
  Node414(Array[Unit]);
  Context415(Array[Int]);
  Vector416(Double);
}

let z417: Bool = !elem289;

enum Value418 {
  Point419(Array[Unit], Unit, Double);
  Buffer420(Bool, Unit, Bool);
  Structure421(Double, Int);
  Record422(Unit);
}

struct List423 {
  tail424: Bool;
  min425: (Int, Bool, Bool, Unit);
  tail426: (Int, Unit, Bool, Double);
  prev427: Unit;
  last428: Bool;
}

let a429: Unit = ();

struct Option430 {
  right431: Int;
  k432: Double;
  value433: Int;
}

let first434: Bool = y160;

struct Entry435 {
  next436: Array[Double];
  prev437: Array[Int];
  bottom438: Int;
}

fn tail439() -> Bool {
  let top440: Double = k332();
  let a441: Tree1 = Tree1::{y2: (i142, 834, status64((), tail94)), data3: ()};
  let _ = a441.y2;
  let _ = a441.data3;
  let _ = a441;
  let item442: Option4 = Option4::{item5: (tail94, 578, 9), item6: (node328, i142, prev368(8, -1), count205), max7: temp280, i8: 408};
  let _ = item442.item5;
  let _ = item442.item6;
  let _ = item442.max7;
  let _ = print_int(item442.i8);
  let _ = item442;
  let i443: Point9 = Point9::{head10: Array::make(10, ())};
  let _ = i443.head10;
  let _ = i443;
  let a444: Instance11 = Instance11::{y12: ()};
  let _ = a444.y12;
  let _ = a444;
  let left445: Container13 = Container13::{temp14: c323, bottom15: 422.9529771376165, index16: false};
  let _ = left445.temp14;
  let _ = left445.bottom15;
  let _ = left445.index16;
  let _ = left445;
  let index446: Data143 = Data143::{node144: -1, left145: false, top146: false, min147: b329};
  let _ = print_int(index446.node144);
  let _ = index446.left145;
  let _ = index446.top146;
  let _ = index446.min147;
  let _ = index446;
  let last447: Value151 = Value151::{y152: temp280, item153: (), data154: (136.92713776621113, 82.80023113612745, true, last155)};
  let _ = last447.y152;
  let _ = last447.item153;
  let _ = last447.data154;
  let _ = last447;
  let z448: Structure157 = Structure157::{node158: temp280, b159: [(), (), node328, i142, i142, ()]};
  let _ = z448.node158;
  let _ = z448.b159;
  let _ = z448;
  let a449: Data189 = Data189::{temp190: (), temp191: 764.2575450288564, next192: c323, first193: Array::make(10, left188)};
  let _ = a449.temp190;
  let _ = a449.temp191;
  let _ = a449.next192;
  let _ = a449.first193;
  let _ = a449;
  let z450: Stack195 = Stack195::{first196: 182.35335007276464, z197: Array::make(6, c323), max198: (elem289, (), 6, 91924), k199: ((), elem214)};
  let _ = z450.first196;
  let _ = z450.z197;
  let _ = z450.max198;
  let _ = z450.k199;
  let _ = z450;
  let current451: Data207 = Data207::{sum208: 783.3541868792952, temp209: prev368(left188, 261), y210: 798, a211: (elem214, prev368(elem214, 96153), i142)};
  let _ = current451.sum208;
  let _ = print_int(current451.temp209);
  let _ = print_int(current451.y210);
  let _ = current451.a211;
  let _ = current451;
  let i452: Queue212 = Queue212::{info213: ((), top132)};
  let _ = i452.info213;
  let _ = i452;
  let z453: Item273 = Item273::{status274: 537.8965832260258, x275: false, b276: top132};
  let _ = z453.status274;
  let _ = z453.x275;
  let _ = z453.b276;
  let _ = z453;
  let left454: Vector281 = Vector281::{node282: false, i283: 80996, value284: 1, info285: left188};
  let _ = left454.node282;
  let _ = print_int(left454.i283);
  let _ = print_int(left454.value284);
  let _ = print_int(left454.info285);
  let _ = left454;
  let j455: Vector286 = Vector286::{value287: result37(), k288: Array::make(6, i142)};
  let _ = j455.value287;
  let _ = j455.k288;
  let _ = j455;
  let k456: Result330 = Result330::{value331: tail94};
  let _ = print_int(k456.value331);
  let _ = k456;
  let elem457: List423 = List423::{tail424: true, min425: (344, y160, elem289, ()), tail426: (545, (), first434, result156), prev427: count205, last428: true};
  let _ = elem457.tail424;
  let _ = elem457.min425;
  let _ = elem457.tail426;
  let _ = elem457.prev427;
  let _ = elem457.last428;
  let _ = elem457;
  let index458: Option430 = Option430::{right431: 52255, k432: k332(), value433: 3};
  let _ = print_int(index458.right431);
  let _ = index458.k432;
  let _ = print_int(index458.value433);
  let _ = index458;
  let head459: Entry435 = Entry435::{next436: Array::make(10, 907.2115058767134), prev437: Array::make(10, 81625), bottom438: 4};
  let _ = head459.next436;
  let _ = head459.prev437;
  let _ = print_int(head459.bottom438);
  let _ = head459;
  let item460: Matrix17 = Matrix17::Wrapper19([(), (), (), (), a429, a429, i142, (), node328]);
  match item460 {
    Matrix17::Queue18(_) => ();
    Matrix17::Wrapper19(_) => ();
    Matrix17::Complex20(_, _, _) => ();
  };
  let _ = item460;
  let data461: Option21 = Option21::Node22(temp280);
  match data461 {
    Option21::Node22(_) => ();
  };
  let _ = data461;
  let c462: Vector23 = Vector23::Queue24(950.338809162793, true);
  match c462 {
    Vector23::Queue24(_, _) => ();
  };
  let _ = c462;
  let left463: Entry25 = Entry25::Point26(409.936551539788);
  match left463 {
    Entry25::Point26(_) => ();
  };
  let _ = left463;
  let flag464: Instance27 = Instance27::Vector29(count194, node328, z417);
  match flag464 {
    Instance27::Node28(_, _) => ();
    Instance27::Vector29(_, _, _) => ();
    Instance27::Queue30(_) => ();
    Instance27::Buffer31 => ();
  };
  let _ = flag464;
  let flag465: Vector33 = Vector33::Option35;
  match flag465 {
    Vector33::Context34 => ();
    Vector33::Option35 => ();
    Vector33::Value36(_) => ();
  };
  let _ = flag465;
  let item466: Option134 = Option134::Instance135;
  match item466 {
    Option134::Instance135 => ();
    Option134::Cache136(_, _, _) => ();
    Option134::Point137(_, _, _) => ();
  };
  let _ = item466;
  let info467: Vector138 = Vector138::Context141(4);
  match info467 {
    Vector138::List139(_, _) => ();
    Vector138::Structure140 => ();
    Vector138::Context141(_) => ();
  };
  let _ = info467;
  let x468: Stack148 = Stack148::Tree150((), [665.6435583872496, 240.38244437601742, result156, top132, 618.970384461245, 340.7244683491478, 529.0980673953712], a429);
  match x468 {
    Stack148::Element149(_, _, _) => ();
    Stack148::Tree150(_, _, _) => ();
  };
  let _ = x468;
  let elem469: Queue201 = Queue201::Matrix204;
  match elem469 {
    Queue201::Structure202 => ();
    Queue201::Vector203 => ();
    Queue201::Matrix204 => ();
  };
  let _ = elem469;
  let status470: Item277 = Item277::Data279;
  match status470 {
    Item277::Result278(_, _) => ();
    Item277::Data279 => ();
  };
  let _ = status470;
  let i471: Point324 = Point324::Buffer326([count194, 667.051543846138, 967.06467822161, 947.7944153865419, 690.0959933122488, 458.3751447791341, prev272], left188);
  match i471 {
    Point324::Value325(_) => ();
    Point324::Buffer326(_, _) => ();
    Point324::Complex327 => ();
  };
  let _ = i471;
  let z472: Instance406 = Instance406::Result409;
  match z472 {
    Instance406::Tree407(_, _) => ();
    Instance406::Node408(_) => ();
    Instance406::Result409 => ();
    Instance406::Object410(_, _, _) => ();
  };
  let _ = z472;
  let top473: Context412 = Context412::Context415(temp280);
  match top473 {
    Context412::Entity413(_) => ();
    Context412::Node414(_) => ();
    Context412::Context415(_) => ();
    Context412::Vector416(_) => ();
  };
  let _ = top473;
  let info474: Value418 = Value418::Buffer420(z417, (), true);
  match info474 {
    Value418::Point419(_, _, _) => ();
    Value418::Buffer420(_, _, _) => ();
    Value418::Structure421(_, _) => ();
    Value418::Record422(_) => ();
  };
  let _ = info474;
  let k475: Bool = result37();
  let _ = k475;
  let _ = status64((), left188);
  let current476: Bool = x95();
  let _ = current476;
  let a477: Double = min161(true, z417);
  let _ = a477;
  let temp478: Double = status215(231.453566066703, tail94);
  let _ = temp478;
  let prev479: Bool = first244();
  let _ = prev479;
  let status480: Double = data290();
  let _ = status480;
  let j481: Double = k332();
  let _ = j481;
  let info482: Int = prev368(-1, 979);
  let _ = print_int(info482);
  110 > tail94
}

fn main {
  let top483: Double = 338.1297493540775;
  let top484: Tree1 = Tree1::{y2: ((), left188, i142), data3: i142};
  let _ = top484.y2;
  let _ = top484.data3;
  let _ = top484;
  let elem485: Option4 = Option4::{item5: (4, last155, elem214), item6: ((), (), tail94, a429), max7: Array::make(8, 6), i8: 4};
  let _ = elem485.item5;
  let _ = elem485.item6;
  let _ = elem485.max7;
  let _ = print_int(elem485.i8);
  let _ = elem485;
  let j486: Point9 = Point9::{head10: Array::make(7, a429)};
  let _ = j486.head10;
  let _ = j486;
  let data487: Instance11 = Instance11::{y12: i142};
  let _ = data487.y12;
  let _ = data487;
  let head488: Container13 = Container13::{temp14: y160, bottom15: 316.7075048661253, index16: y160};
  let _ = head488.temp14;
  let _ = head488.bottom15;
  let _ = head488.index16;
  let _ = head488;
  let tail489: Data143 = Data143::{node144: 1, left145: true, top146: true, min147: (result156, ())};
  let _ = print_int(tail489.node144);
  let _ = tail489.left145;
  let _ = tail489.top146;
  let _ = tail489.min147;
  let _ = tail489;
  let last490: Value151 = Value151::{y152: Array::make(6, last155), item153: i142, data154: (351.50304775300566, 955.057795822544, y160, 558)};
  let _ = last490.y152;
  let _ = last490.item153;
  let _ = last490.data154;
  let _ = last490;
  let left491: Structure157 = Structure157::{node158: Array::make(9, elem214), b159: [count205, (), node328, (), count205, (), (), status64((), 0), ()]};
  let _ = left491.node158;
  let _ = left491.b159;
  let _ = left491;
  let item492: Data189 = Data189::{temp190: status64((), elem214), temp191: 54.99092012208895, next192: true, first193: [9, last155, left188, 3, 41248, 75903, 754, 887, 55903, tail94]};
  let _ = item492.temp190;
  let _ = item492.temp191;
  let _ = item492.next192;
  let _ = item492.first193;
  let _ = item492;
  let value493: Stack195 = Stack195::{first196: 581.1338410959092, z197: Array::make(7, true), max198: (true, node328, 68261, 899), k199: ((), 1)};
  let _ = value493.first196;
  let _ = value493.z197;
  let _ = value493.max198;
  let _ = value493.k199;
  let _ = value493;
  let y494: Data207 = Data207::{sum208: count194, temp209: 4, y210: elem214, a211: (916, 2, ())};
  let _ = y494.sum208;
  let _ = print_int(y494.temp209);
  let _ = print_int(y494.y210);
  let _ = y494.a211;
  let _ = y494;
  let left495: Queue212 = Queue212::{info213: ((), result156)};
  let _ = left495.info213;
  let _ = left495;
  let left496: Item273 = Item273::{status274: 968.3549091990416, x275: z417, b276: 486.9905837082388};
  let _ = left496.status274;
  let _ = left496.x275;
  let _ = left496.b276;
  let _ = left496;
  let top497: Vector281 = Vector281::{node282: z417, i283: 194, value284: last155, info285: 93050};
  let _ = top497.node282;
  let _ = print_int(top497.i283);
  let _ = print_int(top497.value284);
  let _ = print_int(top497.info285);
  let _ = top497;
  let result498: Vector286 = Vector286::{value287: true, k288: Array::make(9, ())};
  let _ = result498.value287;
  let _ = result498.k288;
  let _ = result498;
  let x499: Result330 = Result330::{value331: -1};
  let _ = print_int(x499.value331);
  let _ = x499;
  let c500: List423 = List423::{tail424: false, min425: (36988, false, false, node328), tail426: (8492, a429, false, prev272), prev427: status64(i142, 1), last428: true};
  let _ = c500.tail424;
  let _ = c500.min425;
  let _ = c500.tail426;
  let _ = c500.prev427;
  let _ = c500.last428;
  let _ = c500;
  let info501: Option430 = Option430::{right431: 9, k432: 432.36827462708993, value433: 694};
  let _ = print_int(info501.right431);
  let _ = info501.k432;
  let _ = print_int(info501.value433);
  let _ = info501;
  let node502: Entry435 = Entry435::{next436: Array::make(8, max32), prev437: [1, 1, elem214, elem214, 3, 1, -1, 136, last155], bottom438: 676};
  let _ = node502.next436;
  let _ = node502.prev437;
  let _ = print_int(node502.bottom438);
  let _ = node502;
  let left503: Matrix17 = Matrix17::Complex20(Array::make(8, ()), 914.3904173078531, false);
  match left503 {
    Matrix17::Queue18(_) => ();
    Matrix17::Wrapper19(_) => ();
    Matrix17::Complex20(_, _, _) => ();
  };
  let _ = left503;
  let temp504: Option21 = Option21::Node22(temp280);
  match temp504 {
    Option21::Node22(_) => ();
  };
  let _ = temp504;
  let k505: Vector23 = Vector23::Queue24(620.6855623342835, true);
  match k505 {
    Vector23::Queue24(_, _) => ();
  };
  let _ = k505;
  let y506: Entry25 = Entry25::Point26(top132);
  match y506 {
    Entry25::Point26(_) => ();
  };
  let _ = y506;
  let top507: Instance27 = Instance27::Vector29(576.7409018368679, (), false);
  match top507 {
    Instance27::Node28(_, _) => ();
    Instance27::Vector29(_, _, _) => ();
    Instance27::Queue30(_) => ();
    Instance27::Buffer31 => ();
  };
  let _ = top507;
  let sum508: Vector33 = Vector33::Option35;
  match sum508 {
    Vector33::Context34 => ();
    Vector33::Option35 => ();
    Vector33::Value36(_) => ();
  };
  let _ = sum508;
  let max509: Option134 = Option134::Instance135;
  match max509 {
    Option134::Instance135 => ();
    Option134::Cache136(_, _, _) => ();
    Option134::Point137(_, _, _) => ();
  };
  let _ = max509;
  let first510: Vector138 = Vector138::Context141(-1);
  match first510 {
    Vector138::List139(_, _) => ();
    Vector138::Structure140 => ();
    Vector138::Context141(_) => ();
  };
  let _ = first510;
  let right511: Stack148 = Stack148::Element149(81.72993268357787, left188, false);
  match right511 {
    Stack148::Element149(_, _, _) => ();
    Stack148::Tree150(_, _, _) => ();
  };
  let _ = right511;
  let c512: Queue201 = Queue201::Matrix204;
  match c512 {
    Queue201::Structure202 => ();
    Queue201::Vector203 => ();
    Queue201::Matrix204 => ();
  };
  let _ = c512;
  let c513: Item277 = Item277::Data279;
  match c513 {
    Item277::Result278(_, _) => ();
    Item277::Data279 => ();
  };
  let _ = c513;
  let info514: Point324 = Point324::Value325(0);
  match info514 {
    Point324::Value325(_) => ();
    Point324::Buffer326(_, _) => ();
    Point324::Complex327 => ();
  };
  let _ = info514;
  let x515: Instance406 = Instance406::Node408(temp280);
  match x515 {
    Instance406::Tree407(_, _) => ();
    Instance406::Node408(_) => ();
    Instance406::Result409 => ();
    Instance406::Object410(_, _, _) => ();
  };
  let _ = x515;
  let node516: Context412 = Context412::Context415(Array::make(7, last155));
  match node516 {
    Context412::Entity413(_) => ();
    Context412::Node414(_) => ();
    Context412::Context415(_) => ();
    Context412::Vector416(_) => ();
  };
  let _ = node516;
  let sum517: Value418 = Value418::Point419(Array::make(9, ()), node328, 787.1531105569992);
  match sum517 {
    Value418::Point419(_, _, _) => ();
    Value418::Buffer420(_, _, _) => ();
    Value418::Structure421(_, _) => ();
    Value418::Record422(_) => ();
  };
  let _ = sum517;
  let top518: Bool = result37();
  let _ = top518;
  let _ = status64((), last155);
  let y519: Bool = x95();
  let _ = y519;
  let i520: Double = min161(false, y160);
  let _ = i520;
  let z521: Double = status215(prev272, left188);
  let _ = z521;
  let target522: Bool = first244();
  let _ = target522;
  let min523: Double = data290();
  let _ = min523;
  let value524: Double = k332();
  let _ = value524;
  let node525: Int = prev368(40498, left188);
  let _ = print_int(node525);
  let info526: Bool = tail439();
  let _ = info526;
}


